### ISSUE TITLE
Minecraft 1.7 support

### ISSUE THREAD

**Issue by rutgerkok** [MCTCP/TerrainControl#227]
(Pinging @Wickth, @Timethor and @oloflarsson, hoping one or more of you will help me :smile: . Anybody else is also more than welcome to contribute, just send a pull request. If you don't know how to program in Java, you can help us by testing everything. You can also help by making improvements to the config files to let them look more like vanilla. Post your changed settings here.)

For Minecraft 1.7 a lot of work needs to be done. I have created this issue for us to discuss the technical aspects of the update progress. [See also this forum thread for the less techincal aspects](http://dev.bukkit.org/bukkit-plugins/terrain-control/forum/59849-first-dev-builds-of-bukkit-have-been-released/?unread).

Here's a list of everything that needs to be done. Feel free to add missing points here.

- [x] Get Terrain Control to compile against CraftBukkit
- [x] Get Terrain Control to compile against Forge.
- [x] Create config files for the new biomes.
- [x] Add support for the new blocks
- [x] Add support for the new block rotations (for BO2s and BO3s)
- [x] Add support for the new trees
- [x] Fix the structures (see the classes in the structuregens package, some methods are commented out)
- [x] Fix logging: in the first CraftBukkit build there was another line above each line in the console, in newer builds TC crashes at startup.
- [x] Fix logging: the settings in the PluginConfig don't work at the moment.
- [x] Fix message about duplicate biome id 160.
- [x] Add a more dramatic message when two biome ids conflict to prevent world corruption
- [x] Update snow generation - 1.7 has biomes with snow on mountain peaks only
- [x] Update our ChunkProvider for the changes in ChunkProviderGenerate.
- [x] Merge master into the BiomeInheritance/VirtualBiomes branch
- [x] Add default settings for the flower forest.
- [x] Update default settings for the plains biome.
- [x] Add default settings for the flower forest biome.
- [x] Look into [this SurfaceAndGroundControl bug](http://dev.bukkit.org/bukkit-plugins/terrain-control/forum/59849-first-dev-builds-of-bukkit-have-been-released/?page=5#p96).
- [x] Add support to the grass resource to generate grass in groups.
- [x] Let the Mesa generate correctly for worlds that don't have sea level at 64.
- [x] Check the Mesa colors - [see here](http://dev.bukkit.org/bukkit-plugins/terrain-control/forum/59849-first-dev-builds-of-bukkit-have-been-released/?page=5#p94).
- [x] Fix dirt and gravel ore max height.
- [x] Update gravel generator - [see here](http://dev.bukkit.org/bukkit-plugins/terrain-control/forum/59849-first-dev-builds-of-bukkit-have-been-released/?page=6#p111)

@Timethor is currently working in the BiomeGroups_Simple Branch on (Updated 12-8-14):
- [x] Add initial support for "Biome Groups"  (Almost Done!)
    - [x] User defined groups up to 127
    - [x] New defaults to match the old BiomeList settings
    - [x] BiomeGroup size and rarity
    - [x] Work out the bugs introduced by the changes

@Timethor is also working in the BiomeGroups Branch on (Updated 22-5-14):
- [x] Update Terrain/Biome Generation for 1.7
    - [x] De-obfuscate relevant code to get an understanding of what needs to be updated (ongoing)
    - [x] Layers
        - [x] Get Layers to match 1.7
        - [x] Add back in configuration ability
    - [x] Biomes
        - [x] Add full support for "Biome Groups"
        - [x] Add the new biomes and their variants to the correct group
        - [x] Add the new subbiomes as isles.
    - [ ] Modes
        - [ ] Amplified

Need to view the Minecraft source code? Some helpful links:

* [MCP beta build](https://twitter.com/SeargeDP/status/423188497718333440)
* [mc-dev repo](https://github.com/bukkit/mc-dev)
* [Java decompiler](http://jd.benow.ca/)
* Just run `gradlew setupDecompWorkspace eclipse/ideaModule` to get all Minecraft sources, accessible from your IDE.

**Comment by rutgerkok** [comment]
Already looking *very* similar to vanill. I think this is the most we can get out of TC 2. @Timethor, can I upload this to Spigotmc.org, or do you want to merge your BO3 changes in first?

![world_biome](https://cloud.githubusercontent.com/assets/1462188/6545568/7e41f9de-c58e-11e4-9bf0-7e26b99c42b7.png)

**Comment by Timethor** [comment]
Hmm, the BO3 branch merged in would be nice.

**Comment by rutgerkok** [comment]
Finally, this ticket can be closed.

For the amplified mode: you can make any biome amplified by applying the following formula:

    amplified BiomeHeight = 1 + (BiomeHeight * 2)
    amplified BiomeVolatility = 1 + (BiomeVolatility * 4)
