### ISSUE TITLE
MCPC+ Forge MC 1.6.4 - PopulateChunkEvent Pre/Post is not called for Terrain Control chunks.

### ISSUE THREAD

**Issue by SyncViews** [MCTCP/TerrainControl#236]
These events seem to not be invoked for a world generated by Terrain Control. If Terrain Control is just being used for one dimension, the event still works on the other dimensions (e.g. nether and end).

I can't seem to attach the java source files or compiled files, so the file code is pasted below...

Tested with http://mctcp.com:8900/job/TerrainControl/59/com.khorn.terraincontrol$terraincontrol-release/

I did look in the Terrain Control source and it does look like it should call the event using com.khorn.terraincontrol.forge.EventManager, but I haven't managed to successfully locally build TC or had time to try and attach Eclipse to the existing build to work out what is going on there.

    package wn.terraintesting;
    import net.minecraftforge.common.MinecraftForge;
    import net.minecraftforge.event.ForgeSubscribe;
    import net.minecraftforge.event.terraingen.PopulateChunkEvent;
    import cpw.mods.fml.common.Mod;
    import cpw.mods.fml.common.Mod.EventHandler;
    import cpw.mods.fml.common.Mod.Instance;
    import cpw.mods.fml.common.SidedProxy;
    import cpw.mods.fml.common.event.FMLInitializationEvent;
    import cpw.mods.fml.common.event.FMLPostInitializationEvent;
    import cpw.mods.fml.common.event.FMLPreInitializationEvent;
    import cpw.mods.fml.common.network.NetworkMod;

    @Mod(modid="WillTestMod", name="WillTestMod", version="0.0.0")
    @NetworkMod(clientSideRequired=false)
    public class WillTestMod {
        @Instance(value = "WillTestMod")
        public static WillTestMod instance;
        
        public static class PopulateTest {
            
            public static PopulateTest instance = new PopulateTest();
            
            @ForgeSubscribe
            public void populate(PopulateChunkEvent.Pre event) {
                message(event, "PopulateChunkEvent.Pre");
            }

            @ForgeSubscribe
            public void populate(PopulateChunkEvent.Post event) {
                message(event, "PopulateChunkEvent.Post");
            }

            @ForgeSubscribe
            public void populate(PopulateChunkEvent.Populate event) {
                message(event, "PopulateChunkEvent.Populate");
            }
            
            public void message(PopulateChunkEvent event, String eventStr) {
                String str = eventStr + " called for ";
                str += event.world.getWorldInfo().getWorldName() + " ";
                str += event.chunkX + "," + event.chunkZ;
                
                System.out.println(str);
            }
        }
        
        //@SidedProxy(clientSide="tutorial.generic.client.ClientProxy", serverSide="tutorial.generic.CommonProxy")
        //public static CommonProxy proxy;
        
        @EventHandler
        public void preInit(FMLPreInitializationEvent event) {
            MinecraftForge.EVENT_BUS.register(PopulateTest.instance);
        }
        
        @EventHandler
        public void load(FMLInitializationEvent event) {
            
        }
        
        @EventHandler
        public void postInit(FMLPostInitializationEvent event) {

        }
    }

**Comment by rutgerkok** [comment]
Closing this, as it's an old issue that isn't going to be fixed, unfortunately.
