### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by Noumpas13** [MCTCP/TerrainControl#279]
I run a spigot server 1.7.10 version. I downloaded the latest beta version of TerrainControl 2.6.1 which sais its for CB 1.7.9-R0.11.7.2. When i am trying to install the Folder that is created miss almost everything and its not properly installed and its not working in game (/tc) . I assume its the version compatibility. But i thought it could work with 1.7.10 as it hasnt many differences with 1.7.9. 
Can you verify that 2.6.1 version isnt compatible with 1.7.10? Cause if it does, then there is something else wrong and i cant install TerrainControl. 
If that is the problem, when are you going to release a beta 1.7.10?

**Comment by rutgerkok** [comment]
Closing this issue, as I do not believe this is a bug that needs to be fixed.

By the way, biome group builds can be downloaded from the build server. The default settings are getting really close to vanilla. :smiley:
