### ISSUE TITLE
Cauldron compability issue

### ISSUE THREAD

**Issue by vvswarhead** [MCTCP/TerrainControl#299]
Hello, TC generates map with errors (some biomes became water) if started as cauldron plugin, i dont know how to describe it, please look at screens:
http://grabilla.com/04a01-c01b9df9-6801-4e1f-b3f7-2d0d95731d36.png
(same TC configs, same map, same coordinates, no errors in console)

**Comment by iBars** [comment]
TC not work on Cauldron 1.7.10. I tried v2.6.3 and v2.7.0dev. Even version for mods folder - it requires to be installed on client side...

**Comment by rutgerkok** [comment]
Closing, as bugs appearing on Cauldron aren't going to get fixed, unfortuntely.
