### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by PigheadedGnu** [MCTCP/TerrainControl#316]
A (very cursory) search did not reveal any licensing info. It would be great if it was explicitly mentioned somewhere highly visible like a LICENSE file in the root. Cheers!

**Comment by rutgerkok** [comment]
The current license is stated on [BukkitDev](http://dev.bukkit.org/bukkit-plugins/terrain-control/ (see the sidebar). The project uses the SpoutDev licence, which states that new code is GPL, but automatically changes to MIT after six months.

GPL is problematic for projects depending on closed source software (see CraftBukkit!), so I think  we should use this oppurtunity to change the license to MIT. If all new code from now on gets licensed as MIT, code added by me and @Timethor in the last 6 months gets relicensed to MIT, we'll have a 100% MIT-licensed codebase on March 14, 2015. (This date is exactly six months after the last pull request licensed under the old license.)

The repo does contain some code based on code written by Mojang, which cannot be relicensed as MIT of course. We are techically in violation of Mojang's copyright by publishing derived code. If Mojang enforces its rights, we would be forced to end TC.

So if @Timethor agrees, we can change the license to MIT for all new code and have all existing code relicenced by March 14, 2015. I will then add a licence file explaining the situation to the repo.

**Comment by Timethor** [comment]
Sounds good to me ^_^

**Comment by rutgerkok** [comment]
Added the file. On March 14, 2015 ([π day](http://en.wikipedia.org/wiki/Pi_Day) :smile: ) the project will be licensed solely under the MIT License.
