### ISSUE TITLE
Custom 2x2 Tree sapling growth isn't working correctly

### ISSUE THREAD

**Issue by Masy98** [MCTCP/TerrainControl#318]
I made a new HugeRedwood tree in the biomes config and when i placed 2x2 saplings, only 1 of the 4 saplings were turned in the tree (the one i bone-mealed) PROBABLY because the tree has only 1 origin and it doesn't know in which direction the 3 other vertical lines "expands".

as explained above, it CAN happen that all 4 sapling get replaced with the tree, if i bone-meal the right sapling.

![bildschirmfoto vom 2015-01-25 11 05 29](https://cloud.githubusercontent.com/assets/7923485/5891118/8119c1d2-a482-11e4-81f7-13ccf9bf6ce1.png)

**Comment by rutgerkok** [comment]
Thanks, will look into it later. Which version are you running?

**Comment by Masy98** [comment]
Sorry for the late answer, but i'm using version 2.6.4. Apperrantly i wasn't thinking when i posted this issue but i don't see a real solution for the problem other then have the opportunity to set 4 diffrent "origins"...

**Comment by rutgerkok** [comment]
It seems the rotation of the object is causing the issue. From my testing, the sapling with the lowest x and z is found correctly, but then the object is rotated and doesn't spawn correctly anymore.

**Comment by rutgerkok** [comment]
Should now be fixed. As long as your object expects the trunk to start at (x,z) (0,0), (0,1), (1,0) and (1,1) the object will spawn correctly.

[Download](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/70/default/)
