### ISSUE TITLE
Can't generate a new world in 1.8 with Multiverse

### ISSUE THREAD

**Issue by DarkShimy00** [MCTCP/TerrainControl#319]
When I try to generate a new world with the command "/mv create test normal -s 12 -g TerrainControl" it throws an error in the console and fails to create the world. http://pastebin.com/F02Czy1j

Using git-Spigot-952179b-2173630 (MC: 1.8) and Multiverse 2.5-b639. Tested with TerrainControl 2.6.4 and latest dev build (70).

**Comment by rutgerkok** [comment]
There should have been a message in the console that `test` is not allowed as a world name. Multiverse reserves this name for testing whether a world generator is found in the plugin Terrain Control, so Terrain Control has to ignore this name.

Choose another name for the world and you'll be fine.

**Comment by rutgerkok** [comment]
The message should be there, so I'm reopening this issue to remind myself to test this.
