### ISSUE TITLE
Crash: Biome 161 Redwood Taiga Hills M not found

### ISSUE THREAD

**Issue by Pilvinen** [MCTCP/TerrainControl#320]
TC 2.6.4
Spigot 1.8

Crash report:
http://pastebin.com/RHS494VF

I've been using this same TC version for quite some time without any issues and suddenly I get this.

What is this all about?

**Comment by Pilvinen** [comment]
WorldConfig.ini:

http://pastebin.com/7qirmxyw

**Comment by rutgerkok** [comment]
It's a rare issue appearing in the release builds. It should be fixed in the dev builds, for example in [this one](http://mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/71/default/).

**Comment by Pilvinen** [comment]
Ok, thanks. I updated to the version you recommended.

**Comment by rutgerkok** [comment]
As a release with the above fix is now uploaded to spigotmc.org, I'm closing this issue.
