### ISSUE TITLE
Problem with watermelon who don't appear on jungle biome

### ISSUE THREAD

**Issue by AwaaX** [MCTCP/TerrainControl#321]
Hello, 
Why we don't found watermelon on a jungle biome ?
What can i do for fix that because watermelon don't exist on jungle biome...
Please help

Bye (sorry for my language i'm french).!

**Comment by rutgerkok** [comment]
Should now be fixed: the default settings are now updated to included melons. For existing worlds, you can add `Plant(MELON_BLOCK,1,100.0,0,128,GRASS,DIRT)` to the resources queue of the Jungle biomes. You can also download the [latest dev build](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/73/default/), delete the existing settings and let Terrain Control generate new settings.

**Comment by AwaaX** [comment]
Thanks :)
