### ISSUE TITLE
Problem when generating a map with a plugin

### ISSUE THREAD

**Issue by MrXtr34m** [MCTCP/TerrainControl#323]
Hi !
I have a server crash when i generating a map when my server restart. The code works without TC but with TC it crash every time.
Here is the full stacktrace ->  http://pastebin.com/zHBBvne4 ,other stacktrace http://pastebin.com/DHDhpA4s 

Here is the code ->  http://pastebin.com/afpgf8Hh
loading method -> http://pastebin.com/Kdbhcniw
I have the latest spigot version and the default TC configuration

**Comment by rutgerkok** [comment]
This is simply Spigot getting impatient. If your code takes more than a minute to execute, Spigot kills the server.

TC is a little slower than Minecraft (Bukkit's world generator api is not well designed, which results in a very expensive rewriting process from the chunk format of MC 1.2 to MC 1.8), so your code times out.

You can simply increase the timeout-time in spigot.yml. You can also refactor the code to split up the task, but this is more difficult.
