### ISSUE TITLE
TC build 75-79 crash on start with Spigot 1.8.3

### ISSUE THREAD

**Issue by Pilvinen** [MCTCP/TerrainControl#325]
After updating my server to Spigot 1.8.3 and updating TC to dev versions (tried build 75 and build 79) I keep getting this and the server shuts itself down on start up:

http://pastebin.com/0n3aZsps

And here:

http://pastebin.com/yHim3Ts2

**Comment by rutgerkok** [comment]
This looks like the multiworld bug in Spigot, they [fixed](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/624c97f0813bc4557bed58a22ea35e787bcfe563) it a few builds ago.

If it is not that bug, could you post the output of `/version` so that I can try to reproduce it?

**Comment by Squawkers13** [comment]
Why did you revert it?

**Comment by rutgerkok** [comment]
Because later Spigot versions made this fix not needed anymore. This is a good thing, as the fix broke Multiverse.

**Comment by Squawkers13** [comment]
That makes sense.
