### ISSUE TITLE
'java.lang.NullPointerException' when loading TerrainControl world via Multiverse since 1.8.3

### ISSUE THREAD

**Issue by RoyCurtis** [MCTCP/TerrainControl#326]
Since upgrading to Spigot 1.8.3, one of my worlds that uses TerrainControl as its generator cannot be loaded by Multiverse unless its generator is set to `'null'`

## Details

* Exception: https://gist.github.com/RoyCurtis/60cd5a26f685953b19c9
* World configuration: https://gist.github.com/RoyCurtis/47ceea3295146b571701
* World level.dat: http://i.imgur.com/EvzJ0Di.png
* World config for TerrainControl: https://gist.github.com/RoyCurtis/028fd051347f34756510 (Stone Wasteland.bc: https://gist.github.com/RoyCurtis/5e824e414d9fe960d256 )
* `This server is running CraftBukkit version git-Spigot-26dfd01-5cb9b70 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)`
* Tested with TerrainControl build [83](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/83/)
* `Multiverse-Core Version: 2.5-b692`

## Reproduction

1. Download [the test world](http://gamealition.com/img/derpi.zip) and unzip as folder "world_derpi" in a Spigot 1.8.3 server with Multiverse-Core
2. Add world_derpi's [configuration](https://gist.github.com/RoyCurtis/47ceea3295146b571701) to Multiverse-Core
3. Add world_derpi's [terrain control configuration](https://gist.github.com/RoyCurtis/028fd051347f34756510) to TerrainControl, along with custom biome "[Stone Wasteland.bc](https://gist.github.com/RoyCurtis/5e824e414d9fe960d256)"
4. Run server
5. Do command `mv load world_derpi`. Observe exception in console

**Comment by rutgerkok** [comment]
Your Spigot build is outdated. This Spigot build has the bug [SPIGOT-667](https://hub.spigotmc.org/jira/browse/SPIGOT-667), which is the cause of the above stack trace.

A previous build of TC had a workaround included, but now that the bug is fixed in Spigot the workaround had to be removed.

**Comment by RoyCurtis** [comment]
My bad, you are correct. Updating to the latest Spigot allows the world to load. Thank you!

**Comment by rutgerkok** [comment]
No problem!
