### ISSUE TITLE
Problem loading TerrainControl

### ISSUE THREAD

**Issue by KreWw** [MCTCP/TerrainControl#328]
I had problem running terraincontrol on my recently bought server running multicraft. Basically I'm running spigot 1.8.3 and the latest terraincontrol plugin. So the server doesn't start up if I set terraincontrol generation in the Bukkit.yml for my world, however if I don't set.world.generation in bukkit.yml server starts up. It could be multicraft problem? I have everything setup correctly contacted host and they said to contact dev.

**Comment by rutgerkok** [comment]
Make sure you have the latest version of both Spigot and TerrainControl (so use TerrainControl 2.7.0). If you still have an error, please post the output of the server console here.

**Comment by KreWw** [comment]
Ok I found the cause. It was the spigot.jar that was 1.8.3 but outdated. Is it possible to get terraincontrol working with older spigot 1.8.3 version because currently the newest one crashes most of my plugins. Or atleast tell me the most outdated supported 1.8.3 build.

**Comment by rutgerkok** [comment]
Every Spigot 1.8.3 build from March 11 onwards should work fine.

But pinning yourself on an outdated Spigot build is a great way to get yourself into trouble. Those old builds have a few bugs that allow players to crash the server. Find out which plugins are broken on the latest Spigot, read what they say in the console, search for updates for them, etc.

**Comment by KreWw** [comment]
So your 10k world is only 5kx5k

I flew straight and past 5000 there is only ocean...
