### ISSUE TITLE
TerrainControl 2.7.0 & 2.7.1 make my Spigot 1.8.3 server crash

### ISSUE THREAD

**Issue by Amarski** [MCTCP/TerrainControl#330]
Hi everybody !
I can't use this awesome plugin on my new server as adding it prevents the server from starting...
Two errors messages show up each time : 
- ERROR]: Encountered an unexpected exception
- WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

Could you help me, please ?

**Comment by rutgerkok** [comment]
That error just means that the console does not support all features (like color).

Is there any other error? Does the error still occur if you remove TerrainControl?

**Comment by Amarski** [comment]
Thank you for your answer ;)
The error only occures with TerrainControl because removing the plugin makes everything ok.
I give you my logs and crash reports, maybe you will find something to help me :)
Latest log : http://pastebin.com/c4SkZXpZ
Crash report : http://pastebin.com/jsQPMe6j

**Comment by Amarski** [comment]
Might it be the same error as described here : https://hub.spigotmc.org/jira/browse/SPIGOT-677 ?
If it is, how can I deal with it ?

**Comment by rutgerkok** [comment]
Yeah, based on your server log it is that error. Updating Spigot should fix it.

**Comment by Amarski** [comment]
But I already have Spigot 1.8.3 R0.1, is there a latest version of Spigot than this ?

**Comment by rutgerkok** [comment]
Yes, new builds of Spigot are posted almost daily, as you can see [here](http://www.spigotmc.org/wiki/changelog/). Although their version all starts with Spigot 1.8.3 R0.1, they have a different suffix. Use the `/version` command to see the exact version of your build. Re-run BuildTools to obtain a newer Spigot build.

**Comment by Amarski** [comment]
Ok thank you very much it works all right !
