### ISSUE TITLE
Error when using /tc map world -s 500

### ISSUE THREAD

**Issue by Amarski** [MCTCP/TerrainControl#331]
Hi everybody !
When I try to create an image from my map by using "/tc map world -s 500" there is an error that makes me disconnect when reaching about 60% completed.
Here is the error : 

12:43:23 CONSOLE: ERROR]: Please report this to http://www.spigotmc.org/
12:43:23 CONSOLE: ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
12:43:23 CONSOLE: ERROR]: Spigot version: git-Spigot-4c7d0c0-96c2c39 (MC: 1.8.3)
12:43:23 CONSOLE: ERROR]: ------------------------------
12:43:23 CONSOLE: ERROR]: Server thread dump (Look for plugins here before reporting to Spigot!):
12:43:23 CONSOLE: ERROR]: ------------------------------
12:43:23 CONSOLE: ERROR]: Current Thread: Server thread
12:43:23 CONSOLE: ERROR]: PID: 14 | Suspended: false | Native: false | State: RUNNABLE
12:43:23 CONSOLE: ERROR]: Stack:
12:43:23 CONSOLE: ERROR]: java.util.HashMap.getEntry(Unknown Source)
12:43:23 CONSOLE: ERROR]: java.util.HashMap.get(Unknown Source)
12:43:23 CONSOLE: ERROR]: com.khorn.terraincontrol.generator.biome.CachedBiomeGenerator.getBiomeCacheBlock(CachedBiomeGenerator.java:128)
12:43:23 CONSOLE: ERROR]: com.khorn.terraincontrol.generator.biome.CachedBiomeGenerator.getCachedBiomes(CachedBiomeGenerator.java:176)
12:43:23 CONSOLE: ERROR]: com.khorn.terraincontrol.generator.biome.CachedBiomeGenerator.getBiomes(CachedBiomeGenerator.java:149)
12:43:23 CONSOLE: ERROR]: com.khorn.terraincontrol.bukkit.generator.TCWorldChunkManager.a(TCWorldChunkManager.java:70)
12:43:23 CONSOLE: ERROR]: net.minecraft.server.v1_8_R2.WorldChunkManager.getBiomeBlock(SourceFile:142)
12:43:23 CONSOLE: ERROR]: com.khorn.terraincontrol.bukkit.commands.runnable.MapWriter.run(MapWriter.java:133)
12:43:23 CONSOLE: ERROR]: org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
12:43:23 CONSOLE: ERROR]: org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
12:43:23 CONSOLE: ERROR]: net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718)
12:43:23 CONSOLE: ERROR]: net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
12:43:24 CONSOLE: ERROR]: net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
12:43:24 CONSOLE: ERROR]: net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
12:43:24 CONSOLE: ERROR]: java.lang.Thread.run(Unknown Source)
12:43:24 CONSOLE: ERROR]: ------------------------------
12:43:24 CONSOLE: ERROR]: Entire Thread Dump:
12:43:24 CONSOLE: ERROR]: ------------------------------
12:43:24 CONSOLE: ERROR]: Current Thread: Chunk I/O Executor Thread-1
12:43:24 CONSOLE: ERROR]: PID: 41 | Suspended: false | Native: false | State: WAITING
12:43:24 CONSOLE: ERROR]: Stack:
12:43:24 CONSOLE: ERROR]: sun.misc.Unsafe.park(Native Method)
12:43:24 CONSOLE: ERROR]: java.util.concurrent.locks.LockSupport.park(Unknown Source)
12:43:24 CONSOLE: ERROR]: java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
12:43:24 CONSOLE: ERROR]: java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
12:43:24 CONSOLE: ERROR]: java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
12:43:24 CONSOLE: ERROR]: java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
12:43:24 CONSOLE: ERROR]: java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
12:43:24 CONSOLE: ERROR]: java.lang.Thread.run(Unknown Source)
12:43:24 CONSOLE: ERROR]: ------------------------------
12:43:24 CONSOLE: ERROR]: Current Thread: Netty Server IO #2
12:43:24 CONSOLE: ERROR]: PID: 27 | Suspended: false | Native: false | State: RUNNABLE
12:43:24 CONSOLE: ERROR]: Thread is waiting on monitor(s):
12:43:24 CONSOLE: ERROR]: Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
12:43:24 CONSOLE: ERROR]: Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
12:43:24 CONSOLE: ERROR]: Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
12:43:24 CONSOLE: ERROR]: Stack:
12:43:24 CONSOLE: ERROR]: sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
12:43:24 CONSOLE: ERROR]: sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
12:43:24 CONSOLE: ERROR]: sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
12:43:24 CONSOLE: ERROR]: sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
12:43:24 CONSOLE: ERROR]: sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
12:43:24 CONSOLE: ERROR]: sun.nio.ch.SelectorImpl.select(Unknown Source)
12:43:24 CONSOLE: ERROR]: io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
12:43:24 CONSOLE: ERROR]: io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
12:43:24 CONSOLE: ERROR]: io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
12:43:24 CONSOLE: ERROR]: java.lang.Thread.run(Unknown Source)
12:43:24 CONSOLE: ERROR]: ------------------------------
12:43:24 CONSOLE: ERROR]: Current Thread: File IO Thread
12:43:24 CONSOLE: ERROR]: PID: 32 | Suspended: false | Native: false | State: TIMED_WAITING
12:43:24 CONSOLE: ERROR]: Stack:
12:43:24 CONSOLE: ERROR]: java.lang.Thread.sleep(Native Method)
12:43:24 CONSOLE: ERROR]: net.minecraft.server.v1_8_R2.FileIOThread.c(SourceFile:51)
12:43:24 CONSOLE: ERROR]: net.minecraft.server.v1_8_R2.FileIOThread.run(SourceFile:30)
12:43:24 CONSOLE: ERROR]: java.lang.Thread.run(Unknown Source)

Could you help me, please ?

**Comment by rutgerkok** [comment]
`/tc map` takes a while to execute. This error means that Spigot has lost it's patience. Increase the `timeout-time` in the spigot.yml file or use a smaller radius.

**Comment by Amarski** [comment]
Ok thank you very much !
