### ISSUE TITLE
Missing biomes

### ISSUE THREAD

**Issue by jacobwgillespie** [MCTCP/TerrainControl#334]
Hey!  I'm using the default TerrainControl settings and for some reason cannot find any jungles - is this expected?  My theory is that they are just rare for my seed, but we've generated a radius of 4000 blocks around 0,0 and still no jungles, so I'm starting to wonder if something is up.

Here's our map: http://map.the-obsidian.com/ - there are a few blocks of jungle at -2600,80, but those were manually added.

**Seed:** 4494067228932134328
**Spigot:** CraftBukkit version git-Spigot-2ec6f06-7722428 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
**TerrainControl:** 2.7.1-SNAPSHOT from build 87

Any ideas where to look?  I can't see anything wrong with the config (and it is the default config), and couldn't figure out a way to find biomes by some other means.

**Comment by jacobwgillespie** [comment]
Okay, ignore me, found a natural one - they do seem exceptionally rare though

**Comment by rutgerkok** [comment]
Yeah, it's annoying, but it is how vanilla (and therefore the default settings) generates them. See this vanilla biome map of 10000x10000 area, only one jungle biome visible:

![biomes](https://cloud.githubusercontent.com/assets/1462188/7549421/d1af1cde-f633-11e4-9b07-913a55fad8e0.png)

**Comment by jacobwgillespie** [comment]
Ah, yeah, makes sense...  Can Amidst (or a similar tool) be used to show the output from TerrainControl?  I haven't had any luck generating a map that looks similar to what was generated.  Or is /tc map the only way?

**Comment by rutgerkok** [comment]
`/tc map` is the only way, unfortunately. Luckily the colors of `/tc map` and AMIDST are the same.
