### ISSUE TITLE
Villages not spawning at correct altitude

### ISSUE THREAD

**Issue by Joannou1** [MCTCP/TerrainControl#335]
Been using TC/PHXTM for almost 4 years now, and I must say it never gets old seeing what you can make..

..Although I just recently upgraded the plugin (latest on Jenkins) and started with new configs and am having an interesting issue:
![95023](https://cloud.githubusercontent.com/assets/997747/7664861/08b07a8e-fb52-11e4-9bdb-f2b79faad6c8.png)

On lower terrain the villages tend to be much higher up.
Really odd issue, any idea?

Biome config: 
https://gist.github.com/Joannou1/818a59f4fcc8e4304836

Using latest Spigot/PaperSpigot

**Comment by rutgerkok** [comment]
Minecraft spawns villages at or above the world sea level, but never below. Minecraft uses a single variable for this; per-biome control is not possible. This means that Terrain Control has to use the water level in the WorldConfig for updating this Minecraft variable.

So setting WaterLevelMax to a lower value in the WorldConfig should solve the problem.

**Comment by Joannou1** [comment]
Can't believe I didn't notice that!
Thanks for pointing that out!

**Comment by rutgerkok** [comment]
If you haven't worked with the village code, how could you know that the spawn height of villages is related to the world water level? :smile: 

It's just one of the many quircks in the terrain generation of Minecraft.

**Comment by Joannou1** [comment]
I usually check similarities between things, and I didn't bother with altitude :P 
They all spawned at around the 100 mark, so yeah.
