### ISSUE TITLE
Using modded world generators with TerrainControl

### ISSUE THREAD

**Issue by ajthemacboy** [MCTCP/TerrainControl#338]
Hi, I'm trying to use the mod ATG with TerrainControl and it seems you can't use both.

All I need TerrainControl for is it's structure spawning capabilities. How can I use both ATG and TerrainControl together? And if I can't, can this be implemented? 

Thanks!

**Comment by rutgerkok** [comment]
This would require TC's populator to be used separately, which unfortunately isn't possible. Better mod support is one of the things I hope to do in the future, but I have no idea if/when I will add support.

**Comment by ajthemacboy** [comment]
Alright, thanks :)  I'm not a mod developer, but I believe ATG uses code to reproduce biomes from other biome mods, but in new 'shapes', like Skylands. There might be something there that can help you. In the meantime, the Ruins mod works.. albeit pretty featureless.
