### ISSUE TITLE
Ocean worlds with default settings

### ISSUE THREAD

**Issue by MrPNG** [MCTCP/TerrainControl#346]
So, I didn't change any of the config files, I just put the TerrainControl.jar in the plugins folder, changed the generator in bukkit.yml and deleted my old world and, for some reason, it always generates ocean worlds.

**Comment by RagingGamerChris** [comment]
I'm having the same problem, with the latest version there is. It does not matter if I leave it default or edit it, it just creates and endless ocean world. When will this be fixed?

**Comment by KsenMih** [comment]
You should post your **WorldConfig.ini** here via Pastebin.com (or else).

**Comment by RagingGamerChris** [comment]
There's no point, even the default settings don't work.

**Comment by MrPingu** [comment]
I got something really strange yesterday: I changed a lot of things on the WorldConfig.ini and the BiomeConfig files, and now it generates 'normal' worlds. However, it's 10x slower than it used to be on 1.7. What is even stranger is that the default config doesn't work, but a full personalized one does.

**Comment by RagingGamerChris** [comment]
Can someone give a working WorldConfig.ini ? I want to see if it works.

**Comment by MrPingu** [comment]
This is mine, it's customized to hg, so it has no oceans at all, and I also excluded a lot of biomes. Good luck :smile:
https://gist.github.com/bc9e05aa2c4e7de5187d.git

**Comment by RagingGamerChris** [comment]
I've tried a version like that as well, didn't work. If I set the water level that low, it creates a world with only one endless biome, plains. And if I keep the water level and change land rarity to 100 and land size to 10, it just generates an ocean world.

**Comment by grimmeral** [comment]
TC doesn't take the extra step to make sure you spawn on land. Sometimes it will spawn you on ocean, so try and put some seeds in the generator that spawn you on land, write it down, and always use it.

**Comment by JfromHolland29** [comment]
I'm also encountering spawning in an ocean using TC.
The game tries you to spawn in a "spawn biome" (such as plains, forest, jungle), when that's not possible, it'll spawn you elsewhere. Such as in an ocean.
Isn't it an idea to give the user the ability to change the spawnbiomes in TC? Or the spawn block so you can spawn on sand again like in Beta ;) ? (should I post this elsewhere?)

**Comment by rutgerkok** [comment]
I think nowadays this has been solved. I tried out a few different worlds, and there was always land nearby.
