### ISSUE TITLE
Ravines generating completely wrong

### ISSUE THREAD

**Issue by JfromHolland** [MCTCP/TerrainControl#348]
Look at the image. The ravine is kinda buggy...
![2015-07-28_20 34 30](https://cloud.githubusercontent.com/assets/13544861/8942616/9b379ee2-3576-11e5-9d06-90e7fa3a8c14.png)

**Comment by JfromHolland** [comment]
Every ravine is generating wrong :(

**Comment by rutgerkok** [comment]
![2015-08-11_19 08 16](https://cloud.githubusercontent.com/assets/1462188/9204352/0b5388a8-405d-11e5-8bb4-d8f0052d69ff.png)

Seems fine for me at TerrainControl 2.7.2-SNAPSHOT for Forge.

**Comment by JfromHolland** [comment]
It was in the 1.7 version ;)

**Comment by rutgerkok** [comment]
I'm going to close this ticket, as this bug was fixed a long time ago. Minecraft 1.7 is not supported anymore by us.
