### ISSUE TITLE
TC features quit after certain range of spawn

### ISSUE THREAD

**Issue by greyloon** [MCTCP/TerrainControl#351]
I'll get right to the point. (I'm using the stable release TC for Forge, by the way.) Say I disabled ALL mobs spawning in my world except wolves. For about 8 chunks, I will see only wolves and mob spawning will follow the weight and group number I've specified. However, travelling on for a bit ALL the other passive mobs will start to spawn and in fact wolves ARE NOWHERE to be seen. The passive mobs actually spawn in greater numbers than the default profiles, and are still spawning in a biome that they should absolutely not be spawning in, because they have no entry to spawn off of. Trying to control hostile mob spawning has absolutely no effect at all, not even within the 8 chunk range that the wolves would seem to follow.

Similarly, if I generated an ore with my surface block as the source block and then replaced those blocks with say water, at about that 8 chunk range the ore that spawned on the surface gets replaced much much less than it should. 

It appears to be an issue with how fast the world is explored, as walking over will seem to produce the error much less often, but as for the mobs, especially hostile mobs, it just seems to throw a temper tantrum for no good reason all the time. 

As a side note, the 1.8 version for Forge seems really buggy. I'm sorry, I love the plugin and I think it's great, but from using both the Spigot and Forge versions, the Spigot beats it out in solid coding even though Forge is much more convenient for developing the config files. It might just be the forge version I'm using. Not sure, but I tried to make sure I got the right version when I installed.

**Comment by rutgerkok** [comment]
I could not reproduce any of these issues in the latest Forge build. Today [2.7.2 was released](https://github.com/MCTCP/TerrainControl/releases/tag/v2.7.2), could you please take a look if the issue still happens?

**Comment by grimmeral** [comment]
Thanks for linking me to that page; 2.7.2 on the page I normally get the download from had information on the fixes that got me really excited, but had no download links for some reason, leaving me very disappointed.... I will try it now. However I have a new theory. When I am talking about these spawns, I am generating the world FromImage and it seems to me that where the custom spawn stops working is past the original boundaries of the map.png image. However, custom mob spawning doesn't seem to work at all even INSIDE the boundaries. Also, this seems to be the case for both "Mirror" and "Repeat" options, but I don't believe I tested it with "FillEmpty" yet, which I will do if the same thing happens in the new version.

**Comment by grimmeral** [comment]
Yep, new version, same problems. After a certain distance the spawn lists are completely disrespected, even when the biome is generated normally and not from an image... hostile mob lists do not work whatsoever, not even in the "behavioral range" that the passive mobs do. My chunk loading is being rather slow, perhaps because of the shaders or texture pack I'm using, so I'll see if I'm breaking the generation by making it think it has to go fast and being unable to, making it default or something. Sounds ridiculous, but technology is... well you know.

**Comment by grimmeral** [comment]
Deleted .minecraft, reinstalled TC and Forge with new downloads from the internet, and made sure they were the latest versions... same problem. Also, generating TC worlds after a while with crash the client, generating a new world that doesn't have a folder in the "Terraincontrol/worlds/" directory will crash the client, somehow entering a half px width and height for biome mode:from image with the "continue normal" generation mode selected will not spawn you in the middle of the image, nor will entering negative values.... TC is RIDDLED with bugs in the Forge version.

**Comment by rutgerkok** [comment]
In my testworld, I have the biome ReplacedBlocks setup to only spawn squids, spiders, sheeps and bats, and in that biome there are, as expected, no other mobs.

Could you post one such crash report? It will hopefully contain information about why the mod works fine on my system, but is so broken on your system.

**Comment by grimmeral** [comment]
Here is the log starting at the very first launch of MC today up to the point it decided to crash. I think I generated a world 5 times or so. http://pastebin.com/NSJaihRM

**Comment by grimmeral** [comment]
New bug: sometimes when generating a single player world, a screen will come up before it finishes saying something about connection terminated (next time it happens I'll edit in the exact error) and curiously boots be back to the multiplayer menu even though I created the world in Singleplayer.

**Comment by rutgerkok** [comment]
Those logs don't have any information about TerrainControl or Forge in them, unfortunately. You probably posted the file `.minecraft/logs/latest.log`, and Forge filters all non-vanilla messages out in those files. In the folder `.minecraft/crash-reports` there should be a crash report. The crash report should contain much more information than the log files.

**Comment by grimmeral** [comment]
Sorry, was out all weekend. This is a report from a crash of me generating a new world after I created a new custom biome: http://pastebin.com/TMW7V78d

**Comment by grimmeral** [comment]
Minecraft treats forge like a bad transplant:
http://pastebin.com/Ja0MMZrB

it just seems to not like Forge. I don't understand why. There is no reason it should be trying to delete my damn forge installation....

**Comment by grimmeral** [comment]
I have tried everything. I've deleted and reinstalled minecraft on multiple occasions, and each time I have grabbed new Forge and new TC files and installers of the latest versions, and I have even updated Java a few times just to make sure, then going and reinstalling the whole lot again, and like the process, the errors are repeated, the crashes keep coming, and somehow, now, without changing anything, have become more frequent. I am at a loss.

**Comment by rutgerkok** [comment]
The error http://pastebin.com/Ja0MMZrB is a byproduct of the first error. Java is for cross-platform development, but Minecraft needs to access a few functions native to Windows, and it needs a few temporary files for that. After the game has shut down, those files aren't needed anymore. However, as Minecraft was shut down due to a crash, Windows still thinks those files are in use, so they cannot be deleted immediately. The message informs you that the Minecraft launcher will delete those files later.

Now about the other error (http://pastebin.com/TMW7V78d): does the error also occur if TerrainControl isn't installed? The error message is:

`java.lang.NoSuchMethodError: net.minecraft.client.renderer.texture.TextureMap.<init>(Ljava/lang/String;Z)V`

which looks like there is a mod conflict in the texture map. That doesn't look related to TerrainControl at all. Maybe the specific version of Optifine conflicts with the specific version of Forge?

**Comment by grimmeral** [comment]
Sorry I haven't been able to get back to this. Optifine incompatibility would be a fine answer... if it was installed. Like I said, I started with a new .minecraft folder from scratch and never even put optifine in it to make sure it wasn't causing problems. It's not in, and I'm still getting them.

**Comment by rutgerkok** [comment]
But Optifine appears in your crash log (http://pastebin.com/TMW7V78d) on line 47:

`FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1505 Optifine OptiFine_1.8_HD_U_D1`

There must still be something left of Optifine, and I suspect that to be the cause of the crash.

**Comment by Timethor** [comment]
Has this issue been resolved @grimmeral ?
