### ISSUE TITLE
(Forge) Mob Spawning Not Working

### ISSUE THREAD

**Issue by ThatSoundsFun** [MCTCP/TerrainControl#356]
This bug is most noticeable in deserts. Passive mobs will spawn in deserts the same way as they do in most biomes. The version I'm working on is 2.7.2.

How to Reproduce:
The steps are simplified so others can easily reproduce the bug
1. Create a new world with world type: terrain control 
2. If you don't see a desert, go to the world config file
3. Replace all text in BiomeGroups with this:
   `BiomeGroup(NormalBiomes, 0, 100, Desert`
3. Notice how passive mobs will still spawn despite not spawning normally there in vanilla minecraft

**Comment by Timethor** [comment]
I can't seem to reproduce this... I've been flying around in Forge for about 20 minutes with the latest version of Forge and TC. My world is purely desert and desert hills. Haven't seen any passive mobs. Regular mobs spawn after the sun goes down but no cows/sheep/etc... Hmm.

**Comment by ThatSoundsFun** [comment]
Whoops, I forgot to check the latest snapshot. It seems like the problem was fixed in the snapshot. No passive mobs are spawning in deserts. Also I could fully control the mob settings for custom biomes.

**Comment by Timethor** [comment]
Good to hear, Happy Terra-forming!

**Comment by mensreaMC** [comment]
Would there happen to be any patched versions of the 1.7.10 forge version that fixes this issue?
