### ISSUE TITLE
Minecraft 1.9 Support

### ISSUE THREAD

**Issue by Timethor** [MCTCP/TerrainControl#358]
Minecraft 1.9 seems like it'll be one of the more tame updates. This issue is being created to track and discuss the technical aspects of the update progress.

Here's a list of everything that needs to be done (So far). Feel free to add missing points here.
- [x] Igloos: Spawn in Ice Plains and Cold Taiga (Not hills variant though).
  - [x] Special Spawning of Igloo with extra basement
- [ ] Update BO3Tools to accommodate [Loot Tables](http://minecraft.gamepedia.com/Loot_tables)?

**Comment by rutgerkok** [comment]
An interesting feature is [Loot tables](http://minecraft.gamepedia.com/Loot_tables). Those allow randomized contents of chests or other things (furnaces) by using a combination of NBT and JSON. I would need to update BO3Tools to make this more user friendly.

The village code isn't handled by us, we just call Minecraft's code. This means that we will get the grass paths for free. :smile:

**Comment by Timethor** [comment]
Awesome, I removed the grass path point :D

**Comment by rutgerkok** [comment]
Just updated this issue, as igloos are now in.

**Comment by BakermanLP** [comment]
Loot tables can be assigned via nbt files. Here is a example:
`Block(2,7,1,CHEST,../../nbt/Chests/Chest_simple_dungeon.nbt)`

The content of the nbt file:
`? ''
: - LootTable: minecraft:chests/simple_dungeon
  - Lock: ''
  - id: Chest`

Here is a link to some working nbt files for Minecraft 1.9.4 upwards:
https://github.com/BakermanLP/ProjectRET-AoT/tree/master/templateTC/WorldObjects/nbt/Chests
