### ISSUE TITLE
[BUG] Terrain Control only spawns lower part of some plants (tall grass etc.)

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#365]
Hi there,
terrain control (latest available version) is only generating the lower part of some tall plants. See screenshot attached.
Hopefully you can fix it!

screenshot:
http://i74.photobucket.com/albums/i263/myspaceye/2015-11-17_14-49-16.png

**Comment by JfromHolland29** [comment]
@bloggy isn't that a resource pack or vanilla minecraft issue?

**Comment by Timethor** [comment]
@bloggy @JfromHolland29  Would be nice to know if this is, in fact, not a TC bug...

**Comment by Timethor** [comment]
Closing because I can't reproduce this and no response from OP.
