### ISSUE TITLE
Question: Is there a way to scale up snowfall "limit" ?

### ISSUE THREAD

**Issue by Masy98** [MCTCP/TerrainControl#366]
I've been doing some crazy stuff with my generator and raised the ocean level to 127 and use it as the new "63". The problem with some biomes is, that there is snow, even though there shouldn't be, because minecraft generates snow at a certain point in colder biomes. Is there a way to raise up that "snowfall-height" aswell?

**Comment by JfromHolland29** [comment]
@Masy98: raise the temperature.

**Comment by Masy98** [comment]
I want to have snow on a higher level, but not at >128, if i raise the temperature there will be no snow

**Comment by JfromHolland29** [comment]
@Masy98 Not true. The extreme hills biome has snowfall above y=90, the temperature of the snowless taiga is slightly higher and has snow above y=125.

**Comment by Timethor** [comment]
I agree with @JfromHolland29, if you raise the temp you should see snow start at higher elevations. See [here](http://minecraft.gamepedia.com/Temperature#Temperature) for how to calculate your desired temperature.

I'm closing this issue but please don't feel like you have to stop leaving comments here, I'll still respond.

**Comment by Masy98** [comment]
Yeah, thanks for the help. @NAAVOO wrote me a calculator, you can type in your wished height where snowfall should start and it calculates the Base temperature and even tells you the temperature at your min snowfall height. I assumed that the base temperature counts for Y=64. Here you can test it:
http://temperature.hiroki-studio.com/

**Comment by Masy98** [comment]
My only problem: even if i change the temperature to 0.8 (like in forest biome), there is still snow at height 127 in taiga, but not in forest

**Comment by Timethor** [comment]
Might have to make a cold forest biome :\

**Comment by Masy98** [comment]
So yeah, managed to fix it by converting the biome to a custom biome with a new ID and just set the OverrideBiome to Taiga. Now there is no snow, only problem now is that water spawn as liquid, but slowly freezes. Rivers are totally fine though, just the borders of rivers that are in my custom biome

**Comment by Masy98** [comment]
ok, have found some new issues.. I just can't seem to fix it. If i set the ReplaceToBiomeName to Taiga, it generates with taiga grass color and with no snow, if i turn on rain it starts to snow, even if i set the temperature to 0.8 like in Forest in both, my custom biome and Taiga. If i set ReplaceToBiomeName to Plains, it has the plains grass color and it rains. It seems to me that it doesn't just copy the name like it should... Apperently it copys more than that, but not from the .bc files, because it still snows in taiga if i set the temperature to 0.8 (Besides the fact that it still snows in normal taiga, even if i set the temperature to 0.8 and have it in the normalBiome group). So there seems to be something that overrides my temperature.

**Comment by Masy98** [comment]
SO, I'm at a point where i'm 100% sure that i can't change temperature. No matter what i do, it always snows in Taiga, even if i set the temperature to 10 and it always rains in Plains, even if i set the temperature to 0. To i have to enable something or what...?

**Comment by Masy98** [comment]
Well, apperently my configs are nearly completly ignored... When i change the iceblock to stationary_water water still turn to ice when it freezes, temperature is ignored, grass color is ignored and so on... what have i done wrong when setting up TerrainControl? :D
