### ISSUE TITLE
[ServerCrash] 

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#367]
Just installed Terrain Control and my server crashed after some minutes:

Error from the log files:
http://pastebin.com/r0dN9kUj

Using the Spigot version:
[15:40:51] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Please can you take a look at this?

**Comment by Timethor** [comment]
Hi, the crash log you provided is not that useful by itself as It doesn't show any signs of TC. If you could additionally provide your latest.log file under the logs folder (or whichever log file you saw the crash as) that would be most helpful. Any additional information you can provide would be great too (What configs you changed if any? What other plugins you are using besides TC? etc.)

Thanks!

**Comment by bloggy** [comment]
Maybe it was because of not enough RAM? Is it possible?

**Comment by Timethor** [comment]
Yes, It is possible. If you see this happen again please respond to this issue with your latest.log file under the logs folder so we can see if it is a TC issue or a MC/other plugin issue.
