### ISSUE TITLE
Automatic generate

### ISSUE THREAD

**Issue by SevoX** [MCTCP/TerrainControl#372]
Hey TerrainControl team,
i have Problem. Ist not a issue in this way, but i dont found an better categorie.

At the beginning, my english is not that good, hopefully you unterstand me.

I want to generate a custom Biomes automic, not with an command.

There are three world on my server, and everytime when one was deleted a new world with my custom Biomes should be created(same Name).

Hopefully you understood me and can help me
SevoX

**Comment by Timethor** [comment]
Hmm, I think I understand. Have you tried to NOT set a generation seed for the maps? If no seed is provided you should get a new map. Let me know if this helps :D
