### ISSUE TITLE
ReplaceToBiomeName - Which values are allowed?

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#373]
I have 120 custom biomes and now am going to put the related default minecraft biome names in the config files (ReplaceToBiomeName).

Which values does ReplaceToBiomeName accept? Where can I find a complete list with the correct formatting (upper-lower-case letters) ??

**Comment by Timethor** [comment]
Hey there. You can use the names that are in "double quotes" from [here](https://github.com/MCTCP/TerrainControl/blob/master/common/src/main/java/com/khorn/terraincontrol/util/minecraftTypes/DefaultBiome.java#L80-L209).

**Comment by bloggy** [comment]
Thank you!
And which flower names are correct? Where can I find a list?
example: 
Plant(RED_ROSE,1,80.0,0,128,GRASS,DIRT,SOIL)

**Comment by Timethor** [comment]
Similiar Spot: [here](https://github.com/MCTCP/TerrainControl/blob/master/common/src/main/java/com/khorn/terraincontrol/util/minecraftTypes/DefaultMaterial.java#L18-L215) :D
