### ISSUE TITLE
More ores (diamond, iron etc.) in default biomes?

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#375]
Hi there,
there are few ore blocks in default biomes. How can I scale it up a bit?

**Comment by Timethor** [comment]
Tweak the `Ore` settings in the resource queue of each biome: [check here](https://github.com/MCTCP/TerrainControl/wiki/Resources-queue#ore) and [here](https://github.com/MCTCP/TerrainControl/wiki/BiomeConfigs#resources-queue)

**Comment by Timethor** [comment]
Also, please sign into our [forum](forum.mctcp.com) to get better/faster help from the existing community of TC users. There's only 1-2 people who respond to these issues on a regular basis :D
