### ISSUE TITLE
1.7.10 support

### ISSUE THREAD

**Issue by mensreaMC** [MCTCP/TerrainControl#378]
Thanks for the mod and sorry to bring this up here but I couldn't find any forums or anything to discuss it on. Is the 1.7.10 forge version no longer supported? There is a bug which messes up mob spawning and basically overrides any other mod attempting to change it. I noticed in a changelog that it looks like this issue was fixed, but only for 1.8. Considering a lot of mods have not moved beyond 1.7.10 I was wondering if there's any patched 1.7.10 versions floating around. Thanks for your time and thanks again for the great mod!

**Comment by rutgerkok** [comment]
I'm not going to support it myself, but the code of TerrainControl is open source, so it is possible for someone to update it.

**Comment by mensreaMC** [comment]
Ok, thanks. Do you have a patreon or anything?
