### ISSUE TITLE
Could you mirror the jars on Curseforge?

### ISSUE THREAD

**Issue by joekaiser** [MCTCP/TerrainControl#379]
I was wondering if you could mirror the binaries on Curseforge? I would even be willing to do it if you didn't want to be bothered.

I am asking because I would like to include Terrain Control in a possible pack I am working on. I was going to use Curse Voice to distribute the pack.

**Comment by Timethor** [comment]
@rutgerkok I agree, this is a good idea and we should handle it in an official capacity. Has anything been done so far?

**Comment by rutgerkok** [comment]
@Timethor I have just set one up at http://minecraft.curseforge.com/projects/terraincontrol . Still needs to be approved.

**Comment by rutgerkok** [comment]
As the project on CurseForge is now active, I'm closing this issue. @Timethor, I have added you to the project on CurseForge (same account as for BukkitDev).

**Comment by joekaiser** [comment]
Thanks!

**Comment by Timethor** [comment]
Thanks @rutgerkok  :D
