### ISSUE TITLE
Caves sometimes splits in half

### ISSUE THREAD

**Issue by ThatSoundsFun** [MCTCP/TerrainControl#381]
There's a bug with the current cave generation where a cave could split, creating a 1-3 block thick wall in the middle of the cave. This bug is a lot more noticeable when generating less caves.

Here's a few example of this occurring.
![2015-12-27_21 36 51](https://cloud.githubusercontent.com/assets/13108825/12045007/6937a8d0-ae69-11e5-897b-888118dc25e7.png)

![2015-12-30_17 26 21](https://cloud.githubusercontent.com/assets/13108825/12058470/7d8bae56-af1a-11e5-9300-62e5d054b71e.png)

Edit: Changed the second image because it was at the edge of a cave

**Comment by rutgerkok** [comment]
Isn't this normal vanilla behaviour, but more noticeable because of the low amount of caves?

**Comment by ThatSoundsFun** [comment]
When i was looking at vanilla caves for a while, i found that caves can still split, but most of it is at the edge where the cave is thin. In TC i notice them more at the middle of caves system where the cave were not that thin. That second picture is probably not a good example since its at the edge of a cave.
