### ISSUE TITLE
Event API

### ISSUE THREAD

**Issue by liec0dez** [MCTCP/TerrainControl#396]
I highly request the implementation of public Bukkit Events for the spawning of BO2/3 objects.
Specifically the **canCustomObjectSpawn** method in [EventHandler.java](https://github.com/MCTCP/TerrainControl/blob/master/common/src/main/java/com/khorn/terraincontrol/events/EventHandler.java)

Thanks in advance!

**Comment by rutgerkok** [comment]
Can't you just call `TerrainControl.registerEventHandler(yourListener)`? What benefit would using Bukkit events provide?

**Comment by liec0dez** [comment]
Wow I overlooked that method, thanks :3
