### ISSUE TITLE
Terrain Control + Dynmap issues

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#398]
Hi there,
in reply to this thread:
https://github.com/MCTCP/TerrainControl/issues/395
I have downloaded and tested your version. Console errors are not showing up anymore BUT dynmap still does not render anything.
Can you check it out?

**Comment by rutgerkok** [comment]
I haven't had time to look at it yet.

**Comment by bloggy** [comment]
Ok, hope you'll find the time soon as I need this fixed asap. Let me know if I can be of any help for you!

**Comment by bloggy** [comment]
Screenshot of /dynmap stats
http://i74.photobucket.com/albums/i263/myspaceye/2016-04-01_14-43-38.png

**Comment by Rasor1911** [comment]
Posted something to do with this on the dynmap github
https://github.com/webbukkit/dynmap/issues/1908

**Comment by rutgerkok** [comment]
Today I got a chance to install Dynmap.

I created a world with the Worldconfig and BiomeConfig of @bloggy . I had to remove most of the custom biomes, as I don't have the config files for them (the default biome config settings aren't suitable for biomes with ids > 255).

Then I installed Dynmap. See my console log [here](http://pastebin.com/A0xrTgUe). On line 39 we see that it correctly picked up all custom biomes. After a `dynmap fullrender world`, we can see the result in the browser:

![image](https://cloud.githubusercontent.com/assets/1462188/14226860/f66c06ae-f8ee-11e5-9da2-ee4276d968c4.png)

So, I cannot reproduce the bug.

One thing I would try is to reset the world map: (re)move the `plugins/Dynmap` folder. If that also doesn't help, then I'm going to need some more complete testworld where this bug does happen. (The world with monolitouter doesn't cause problems for me, as you can see.)

**Comment by bloggy** [comment]
Thanks for your help, I think deleting the dynmap folder with all subfolders fixed the issue for me.

**Comment by rutgerkok** [comment]
That's annoying, but at least you got it working.

I suspect this happens because Dynmap now knows about TerrainControl's custom biomes. I hope this doesn't happen every time you add a new custom biome...
