### ISSUE TITLE
Bo3 Objects spawn with height variance even when restricted to 1 block of height

### ISSUE THREAD

**Issue by Piginabag** [MCTCP/TerrainControl#404]
When a bo3 object is told to spawn at, say, heights 15 to 15, the object will spawn with at least 1 block of height variation (in my case, 15 to 16). TC 2.7.2

**Comment by Timethor** [comment]
Fixed by 11bb54fd, Thanks for the bug report here :smile: 

Forum topic for cross reference: http://forum.mctcp.com/t/bo3-objects-spawn-with-a-1-height-variance/888/8
