### ISSUE TITLE
WorldBorder crash's

### ISSUE THREAD

**Issue by jordanwilliams1** [MCTCP/TerrainControl#419]
Hi,

I'm trying to genertate a world. But when i try to world border crash's after a few hours. I'm using the biom pack with over 300 bioms.

Here's my error: http://hastebin.com/arotalileg.avrasm
Here's the biom pack: https://sites.google.com/site/biomebundle/

**Comment by rutgerkok** [comment]
This should now be fixed in the latest dev build.
