### ISSUE TITLE
Can't generate recource Ore

### ISSUE THREAD

**Issue by Wolf2323** [MCTCP/TerrainControl#427]
I'm running on TC 2.8.0 and Spigot 1.9.2-R0.1-SNAPSHOT.
And I am trying to generate a new Ore. For this I have added the line "Ore (GLOWSTONE, 2,1,20.0,0,64, STONE)" in each Biome. But no Glowstone is generated.

**Comment by rutgerkok** [comment]
(We must have missed this issue. I don't think @Wolf2323 is still interested in a solution, but I'm replying here anyways in case someone with a similar problem finds this page using a Google search.)

I think the space between `Ore` and the `(` is the problem.

I would just copy the line with the DIRT ore from one biome, then put it into your biome, and replace DIRT with GLOWSTONE.
