### ISSUE TITLE
Forge client showing all custom Terrain Control biomes as Plains

### ISSUE THREAD

**Issue by Qohelethh** [MCTCP/TerrainControl#428]
I am using Biome Bundle configs and the custom build of Terrain Control that comes with it, so I'm not sure if this is an okay place to ask this, but it seems to be a Terrain Control issue.

I set up a Forge server running the Biome Bundle custom biomes and everything seems to generate correctly. However, when I connect to the server with a Forge client that is also running the same version of Terrain Control, all custom biomes appear to be Plains biomes. Grass/foliage color, etc all appear as if it were a Plains biome.

The names of the two Terrain Control jars I am using client and server-side are as follows. Both are in the mods directory in the client and server:
terraincontrol_common-2.72 for Forge 1.7.10 v4.jar
terraincontrol-forge-2.7.2 for Forge 1.7.10 v4

I am running Forge 1.7.10 version 10.13.4.1614.

**Comment by rutgerkok** [comment]
That version is made by @PG85, so he would be the one to help. The official 2.7.2 only runs on Minecraft 1.8.

**Comment by Qohelethh** [comment]
Thanks! I messaged him on the TC forums.

**Comment by PG85** [comment]
Hey Qohelethh,

Thanks for the bug report, looks like a problem with packets. I intend to finish new versions of MCW for MC 1.7.2 and 1.8.9 this weekend, after that I'll take another look at TC 2.7.2 for MC 1.7.10. So most likely I'll fix this next week and have a release ready in the weekend.

**Comment by Qohelethh** [comment]
Thanks for the response! I look forward to testing out the next release.

**Comment by Qohelethh** [comment]
I found one new bug which I think is connected to this version of TV. You know how when Minecraft terrain generation places caves through sand, it will place sandstone in an attempt to prevent all the sand from falling? When this happens with this version of TC in red sand, it will place a weird block under the red sand, like a sapling, which results in bizarre terrain gen.

**Comment by rutgerkok** [comment]
I'm marking the issue as closed because it's not a bug in TerrainControl. The discussion is not locked, so you can continue posting here if you want.
