### ISSUE TITLE
Internal error keeps happening

### ISSUE THREAD

**Issue by countryrose12** [MCTCP/TerrainControl#429]
this is what it shows for me! i have tried other version of it and the same error!

rg.bukkit.command.CommandException: Unhandled exception executing command 'tc' in plugin TerrainControl v2.8.1-SNAPSHOT
20.05 21:19:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_95]
20.05 21:19:57 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_95]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit1.8.8.jar:git-Bukkit-efe04b8]
20.05 21:19:57 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
20.05 21:19:57 [Server] INFO Caused by: java.lang.NullPointerException
20.05 21:19:57 [Server] INFO at com.khorn.terraincontrol.bukkit.TCPlugin.onCommand(TCPlugin.java:111) ~[?:?]
20.05 21:19:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit1.8.8.jar:git-Bukkit-efe04b8]

**Comment by rutgerkok** [comment]
TerrainControl v2.8.1-SNAPSHOT is for Minecraft 1.9.4, and you are running Minecraft 1.8.8. Download an older version of TerrainControl [from here](https://github.com/MCTCP/TerrainControl/wiki/Version-history#recommended-build-for-each-minecraft-version).

**Comment by countryrose12** [comment]
i have tried the 1.8.8 version and it does the same thing kid.

On Sat, May 21, 2016 at 8:41 AM, Rutger Kok <notifications@github.com>
wrote:

> TerrainControl v2.8.1-SNAPSHOT is for Minecraft 1.9.4, and you are running
> Minecraft 1.8.8. Download an older version of TerrainControl from here
> <https://github.com/MCTCP/TerrainControl/wiki/Version-history#recommended-build-for-each-minecraft-version>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MCTCP/TerrainControl/issues/429#issuecomment-220778403>
>



-- 
*Un thoughtful memories shall not make me fear things!*

**Comment by rutgerkok** [comment]
Make sure you have overwritten the other TerrainControl file.

It would also help if you post the error you are currently getting. If it's the same, line for line, as the one above, then we know for sure that the other TerrainControl file is still around, and you'll need to overwrite that with the one I linked.
