### ISSUE TITLE
Please update to 1.10 !

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#432]
Terrain Control does not work with 1.10 - please update ! :-)

**Comment by TheChampTF** [comment]
The issue http://paste.yu8.me/?c6ed529fe6ee4be0#tJLAPg8YqokDP8t0I0fHbA3zqZjSu8JUz7yvRGh9mqA=

**Comment by rutgerkok** [comment]
Fixed in [latest dev builds](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/).
