### ISSUE TITLE
Bug in generator

### ISSUE THREAD

**Issue by Culvanen** [MCTCP/TerrainControl#433]
> [Server] WARN This is a bug in the generator plugin, NOT a bug in Multiverse!
> [Server] WARN Failed to set the generator for world 'test' to 'TerrainControl':
> java.lang.NullPointerException: The validated object is null

**Comment by rutgerkok** [comment]
Could you post the rest of the error? While these lines are the most useful for you, they don't contain any information for us to resolve the issue.

**Comment by Culvanen** [comment]
there is no more error juste that's

**Comment by rutgerkok** [comment]
There must be other lines nearby containing stuff like `at com.khorn.terraincontrol`, but maybe your admin panel doesn't display them.

What I would try:

* create a world with another name - the name 'test' sometimes causes problems, as that name is also used internally by Multiverse for several tests.
* make sure you have the correct TerrainControl version for your Minecraft version -- see the [table over here](https://github.com/MCTCP/TerrainControl/wiki/Version-history#recommended-build-for-each-minecraft-version).

**Comment by Culvanen** [comment]
Ok, thanks
