### ISSUE TITLE
Invalid resource BiomeGroup

### ISSUE THREAD

**Issue by TheChampTF** [MCTCP/TerrainControl#436]
On latest dev. build I'm now getting http://paste.yu8.me/?3faf540a0cfcf922#7DaURFNgKzpoReMwhOPZf5nQSgKQJlFluNz4Y6HqMYg=

**Comment by rutgerkok** [comment]
This should now be fixed: http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/149/default/

**Comment by TheChampTF** [comment]
Yes, thanks a lot.
