### ISSUE TITLE
Placement of tripwire crashes server (IllegalStateException: Chunk is already being populated)

### ISSUE THREAD

**Issue by craftyjai** [MCTCP/TerrainControl#438]
Whenever loading new chunks the server will sometimes crash
Below is the crash
http://pastebin.com/k1T9PU43

I am using the latest dev build

**Comment by rutgerkok** [comment]
In the last few builds, I did some work towards fixing this issue. Could you test [build 156](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/156/default/) and report whether this issue still occurs?

**Comment by craftyjai** [comment]
I will test build 156

**Comment by craftyjai** [comment]
That error is gone but is this related http://pastebin.com/w5jGjDMS

**Comment by craftyjai** [comment]
I just got this crash also http://pastebin.com/YRDCFG4Q

**Comment by rutgerkok** [comment]
About the [first error](http://pastebin.com/w5jGjDMS): no idea what's causing it, TerrainControl doesn't seem to be involved.

The second error should now be fired in build 157.
