### ISSUE TITLE
1.9.2 Invalid Generator

### ISSUE THREAD

**Issue by CDXTHEEVIL** [MCTCP/TerrainControl#441]
Used the command:
/mv create AcerX -g TerrainControl
and got the error message from Multiverse:
Invalid Generator! 'TerrainControl'. Aborting world creation

**Comment by mcsnetworks** [comment]
Make sure TerrainControl is actually loading.  the "invalid generator" error typically means its not loaded.

**Comment by rutgerkok** [comment]
The complete contents of the server console would be really useful, now I cannot help you.

**Comment by bloodmc** [comment]
Not enough information.
