### ISSUE TITLE
Forge / Sponge 1.10 biome ID > 256 error

### ISSUE THREAD

**Issue by mcsnetworks** [MCTCP/TerrainControl#442]
Hello,  I am using: terraincontrol-forge-2.8.2-SNAPSHOT.jar, under: spongeforge-1.10.2-2011-5.0.0-BETA-1567.jar.

Error:  java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.

I attempted to load a previously loaded world and apparently ran out of Biome ID's.  Note:  previously this world worked fine under Cauldron 1.7.10.

Error Log:  https://gist.github.com/mcsnetworks/f9b1791ff921a10e9b8ef7ff900fea39

WorldConfig.ini:  https://gist.github.com/mcsnetworks/7d82ce38d4693d005d171a68b9546f21

Thoughts?

**Comment by rutgerkok** [comment]
Yeah, the Forge version is not really useable at the moment. Zidane suggested a fix using a placeholder biome, I will have to try something like that.

**Comment by mcsnetworks** [comment]
Hello.  Does your latest Forge commits address this issue?

**Comment by rutgerkok** [comment]
Not really. The crash should be gone, but the biome will show up as if it were the Plains biome.

**Comment by mcsnetworks** [comment]
Does that mean that any biome ID that gets registered past 256 will be completely broken?

**Comment by rutgerkok** [comment]
The biome won't be registered, so it will show up as an unrecognized biome. Minecraft displays these as the plains biome.

**Comment by mcsnetworks** [comment]
@rutgerkok from a generation stand point will it still work when the register with this message?

12:22:42 AM [INFO] [TerrainControl] Asked to register Grand_CRocksBorder with id 268, but succeeded with id 0
12:22:42 AM [INFO] [TerrainControl] Asked to register NethersCave with id 202, but succeeded with id 0
12:22:42 AM [INFO] [TerrainControl] Asked to register CanyonClosed with id 266, but succeeded with id 0
12:22:42 AM [INFO] [TerrainControl] Asked to register Nethers with id 128, but succeeded with id 0
