### ISSUE TITLE
World seams / seed change on server restart (1.9 + 1.10)

### ISSUE THREAD

**Issue by MCPitman** [MCTCP/TerrainControl#444]
Just wanted to officially report [this](http://forum.mctcp.com/t/terraincontrol-for-spigot-1-10/1011/49) as a bug here on the bug tracker. Some more details in the links below:

http://forum.mctcp.com/t/terraincontrol-for-spigot-1-10/1011/44

https://www.reddit.com/r/biomebundle/comments/4qh9jz/bug_report_dont_know_if_its_an_terraincontrol_or/

I can confirm that there is no error in the log concerning level.dat corruption (as first suggested by rutger).

The bug is easily reproduced by loading up Biome Bundle in Spigot 1.9/.1.10 as it happens every time the server is restarted. (if doing so be sure to change population bounds check to false to stop the tripwire bug crashing things).

**Comment by MCPitman** [comment]
After more testing of workarounds for this issue it has been discovered that specifying a seed in server.properties as well as in the worldconfig.ini seems to prevent it. Hope that helps in narrowing down the cause :)

**Comment by afroman84** [comment]
yes, actually this issue is not solved even with defined seed in server.properties

**Comment by lumiru** [comment]
I tried last SNAPSHOT version and I got the same issue (despite  6bdbdc1).

See generated TC map results for seed 6521433701164005167 : 
![world_biome](https://cloud.githubusercontent.com/assets/4085705/19013814/60ec90ee-87dc-11e6-9ab6-e45f76ec1915.png)
![world_biome autre copie](https://cloud.githubusercontent.com/assets/4085705/19013816/60f68a18-87dc-11e6-8622-b3de2aab7d28.png)
![world_biome copie](https://cloud.githubusercontent.com/assets/4085705/19013815/60f1f8cc-87dc-11e6-91b2-3089bfa7bccd.png)

![2016-10-01_13 37 46](https://cloud.githubusercontent.com/assets/4085705/19013823/a0564c16-87dc-11e6-9c26-3f3ced2b9ed5.png)

As you can see, biome borders are nearly the same but not biome types.

**Comment by lumiru** [comment]
After some tests, I can say the bug appears between build 115 (1c7e84d) and 120 (6a03ea2).
_Before 115, I always get the same /tc map result and after 120, I always get different /tc map result at each restart._
I cannot be more precise because of crashes in these intermediary builds.

**Comment by rutgerkok** [comment]
Thank you very much, that narrows down the search considerably. [All changes](https://github.com/MCTCP/TerrainControl/compare/1c7e84d1d597610e375b4b3658b45a043f6bdd6f...6a03ea2428fd09052236dbc0aeb5c97e1b3bba28) between 120 and 115 are:

1. Fix ReplaceToBiomeName not working bce4c345b942f11bdc6ae1b27a0aa41aef1b0d37
2. Don't automatically sort resources queue 91fe6bcaf1e177a2a4dca957fb9c268254b58aea
3. New biome: The Void ca094ff353ba44749de8c8277c2957a2d089ef60
4. Fix another bug in ReplaceToBiomeName  ae33ee8b93fcd17ab20ee95dcf1f07c7bd1fbc68
5. And fix another bug in ReplaceToBiomeName  d945f36afbdd94abc5a02292c6367a9a436e8cba
6. Forgot one line of code 6a03ea2428fd09052236dbc0aeb5c97e1b3bba28

If I just look at this, I would guess it has something to do with ReplaceToBiomeName... That's not at all where I expected the bug to be.

**Comment by lumiru** [comment]
I checked out bce4c34 and apply patches of commits d945f36 and 6a03ea2 on it and the bug occurs so it would be in one of these 3 commits.

**Comment by afroman84** [comment]
are there any news on solving this? thank you :)
