### ISSUE TITLE
Forge and NBT Tags for MobSpawner

### ISSUE THREAD

**Issue by BakermanLP** [MCTCP/TerrainControl#450]
Hello there,
I am trying to create a world and wanted to implement Mob Spawner in some Custom Objects. 

Here is a demonstation world config: http://bakermanlp.de/files/HellTest.zip

The Spawner are created, but the NBT files are not assigned or anything like that. Same with chests here.

Minecraft 1.10.2, Forge 2073, Terrain Control Build 159

Also there seems something to be with debug and trace logs. I can't see them in any logfile.

In an older Spigot 1.9.4 environment this world is working and nbt tags are assigned.

Would be great if someone can help me.

Thanks

Michael (aka BakermanLP)

**Comment by Maxqia** [comment]
In your BO3 configs, it doesn't seem like you assigned your chests a nbt file ...

**Comment by BakermanLP** [comment]
This issue is solved. There were two errors. First the nbt file was not correct for 1.10.2 and my bo3 files were messed up.
