### ISSUE TITLE
problem with bo3tools and –tileentities

### ISSUE THREAD

**Issue by ZoefyC** [MCTCP/TerrainControl#451]
Everytime I try to export structures with hoppers, furnaces, spawners, traps, command blocks etc. in it, I get an error message saying "An internal error occurred while attempting to perform this command". I don't get this error with empty chests, though.
This is the command I'm using: /exportbo3 name --includetileentities
This is the error I get in console:  [http://pastebin.com/XjtGfyj2](http://pastebin.com/XjtGfyj2)

I'm using spigot 1.10.2 version Spigot-1e4dd71-5e5cf84, build 152 of terrain control and the v1.6-SNAPSHOT of bo3 tools (rutgerkok suggested this version on the TC forums).

**Comment by Noumpas13** [comment]
I cannot export any bo3. I get the same error. BO3Tools are outdated (using tc 2.8.2 snapshot). Rutgerkok please?

**Comment by ZoefyC** [comment]
Try using the versions Rutgerkok mentioned on the forums, they work with everything but tileentities. 
Link: http://forum.mctcp.com/t/terraincontrol-for-spigot-1-10/1011/

**Comment by Noumpas13** [comment]
i already have tc 2.8.2 snapshot. i always use the latest dev builds.
the problem is at BO3Tools not tc

**Comment by ZoefyC** [comment]
As I said, use the versions (tc and bo3) mentioned in the post. They work except for tileentities.

**Comment by Noumpas13** [comment]
You are talking about downgraded versions. I currently use the latest versions. these files have a name. Can you tell me which versions are you using. I really dont want to downgrade and mess up with everything else and cause error shutdowns and server kills just for the bo3 to work.
tc: 2.8.2 Snapshot
bo3: 1.5

**Comment by ZoefyC** [comment]
I'm sorry but did you even read my post or the forum post?

"I'm using spigot 1.10.2 version Spigot-1e4dd71-5e5cf84, build 152 of terrain control and the v1.6-SNAPSHOT of bo3 tools (rutgerkok suggested this version on the TC forums)."

**Comment by Noumpas13** [comment]
i ve just noticed, you said 1.6 snapshot... where can i find that

**Comment by ZoefyC** [comment]
Link to the forum post: http://forum.mctcp.com/t/terraincontrol-for-spigot-1-10/1011/36?u=zoefyc

Link to the working bo3tools: https://dl.dropboxusercontent.com/u/23288978/BO3Tools.jar

**Comment by Noumpas13** [comment]
Indeed, it doesnt save entities inside the chests

**Comment by Noumpas13** [comment]
Hey ZoefyC, Rutgurkok fixed the bugs.
Here is the fixed version:
http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/162/default/

**Comment by ZoefyC** [comment]
Awesome! Thank you, I'll check it out :)
