### ISSUE TITLE
TerrainControl Problem with Chests and mob heads

### ISSUE THREAD

**Issue by Noumpas13** [MCTCP/TerrainControl#457]
I know that BO3 have already a bug with entities, but i dont know if this issue is similar with it. I have some BO3 structures and when they spawn in the biomes, if there are any chests / trapped chests / ender chests / mob heads, they are not displayed. It just shows you something is there (you can see their block lines but they are invisible). When you open the chests, they make no sound. If you Open one and then modify a sourrounding block, they appear but still no sound of an opening chest. Mob Heads and Chests when destroyed, leave their entity down.

https://s16.postimg.io/cod8ngyoj/2016_09_08_22_11_28.png

https://s16.postimg.io/ph1cneaab/2016_09_08_22_11_34.png

https://s16.postimg.io/og13y9tar/2016_09_08_22_11_57.png

https://s16.postimg.io/he7rptf2r/2016_09_08_22_12_16.png

https://s16.postimg.io/5dmbp37o3/2016_09_08_22_12_22.png

https://s16.postimg.io/5ew9ii9hv/2016_09_08_22_14_16.png

https://s16.postimg.io/xgaaw7es3/2016_09_08_22_14_22.png

https://s16.postimg.io/bidu2ezrn/2016_09_08_22_14_26.png

https://s16.postimg.io/688vb4fir/2016_09_08_22_14_33.png

*UPDATE*
Its not BO3's problem but TC's, when i try to spawn Chests/mob heads directly from the Biome's config, they also spawn invisible
https://s9.postimg.io/72rltue71/2016_09_08_23_15_19.png

Also see:
http://forum.mctcp.com/t/problem-with-chests-mob-heads-with-bo3/1150/6

**Comment by rutgerkok** [comment]
With a bit of luck, [build 162](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/162/default/) fixes this issue.

**Comment by Noumpas13** [comment]
Yeah it is fixed. nice work rutgerkok
