### ISSUE TITLE
ReplaceToBiomeName not working

### ISSUE THREAD

**Issue by lightningo7** [MCTCP/TerrainControl#458]
I have several biomes set to replace to biome names and upon boot it says that they registered with biome ID 0.

TerrainControl v forge-2.8.2

**Comment by mcsnetworks** [comment]
This is a known issue.  The previous patch rut applied to the forge version was just duct tape to prevent the server crash.

**Comment by mcsnetworks** [comment]
FYI @lightningo7 I am working to resolve this issue.

**Comment by lightningo7** [comment]
Any ETA on when it'll be fixed? I look forward to having this working.

**Comment by bloodmc** [comment]
@mcsnetworks @lightningo7 Test my patched jar here

https://www.dropbox.com/s/6ioy6jgc2nuk1gn/terraincontrol-forge-2.8.2-SNAPSHOT.jar

Backup your world before testing. Please confirm if it works and I'll PR the fix so everyone benefits.

**Comment by Inscrutable** [comment]
I've tested this with Forge 2185 (and SpongeForge 1.10.2-2171-5.1.0-BETA-1992) , and blood's test build holds water. ``Replacetobiome`` worked as expected; the test biome **Flard** (ID 666) generated as an amplified desert yet reported as a _Flower Forest_ (ID 132). No errors whatsoever on console.
Forge's biome registration changed sometime in the past, this has probably been around a while.
This is also probably the same bug as Terrain Control issue #442

**Comment by mcsnetworks** [comment]
I'll test this evening.
