### ISSUE TITLE
Differences in terraingen with new snapshot 162 ?

### ISSUE THREAD

**Issue by saturnineNL** [MCTCP/TerrainControl#461]
I just downloaded and installed the newest snapshot (Build #162)
And when i generated my world, it seems that the generation is
different from the old snapshot. 

[old and new terrain gen images](http://imgur.com/a/HL8qQ) 

Dont look at the weird textures, i am experimenting with them :slight_smile:
Its the terraingeneration itself that is different. I didnt change anything to the
config files (instead i switched the plugins to make these images)

The biome you're looking at gets its settings from a generic mountain biome
(its extended), the biome config can be found here : 

[biome config file](http://pastebin.com/5up6HB5b )

Greets Sat

**Comment by rutgerkok** [comment]
There are indeed some differences. Today, I reverted the code to how it was before March 9 of this year, so that the terrain should look like TerrainControl 2.7. If you still have a server on Minecraft 1.8 somewhere, you can verify that the old behaviour is restored.

**Comment by saturnineNL** [comment]
I saw that on github. I recently started with MC again, so i dont have a 1.8 world. The reason i posted it this was that you might have missed some parts of the recode. Now that i know its intended i'll find a way
to work with it. Thanks for keeping terraincontrol alive i would be lost without it :)

greets Sat
