### ISSUE TITLE
problem with villages

### ISSUE THREAD

**Issue by ZoefyC** [MCTCP/TerrainControl#463]
There are some problems with villages:
- Villages spawn without any villagers or chests
- "VillageDistance" in WorldConfig doesn't work properly. If set to 64, there are still several villages spawning right next to each other
- Villages are spawning way too high up in the air, sometimes 5-10 blocks (even in flat areas)

I'm using TC build #162 on Spigot 1.10.2 version 9797151-301db84

**Comment by chezpaul** [comment]
I second that. I have tons of villages and 25% of them are way up there in no man's land.

**Comment by Noumpas13** [comment]
I would rather have them completely disabled than having these monstrosities as villages

**Comment by chezpaul** [comment]
It seems like the villages up in the air is not TC's doing.
This happens without TC. It must be Multiverse. It doesn't happen in single player

**Comment by Noumpas13** [comment]
Good, lets go bash them too then

**Comment by bloodmc** [comment]
Create another ticket if this occurs with only TC and latest builds.
