### ISSUE TITLE
BiomeSizeWhenIsle, BiomeRarityWhenIsle and BiomeSizeWhenBorder don't do anything.

### ISSUE THREAD

**Issue by MCPitman** [MCTCP/TerrainControl#471]
Easy reproducible; create an edge biome in random mode and play around with BiomeSizeWhenBorder, then change BiomeSize (which shouldn't do anything to a border biome) and watch it change.

Isle biomes also use BiomeSize / BiomeRarity and not BiomeSizeWhenIsle / BiomeRarityWhenIsle.

Using TC build 163 in Spigot 1.10.2 in BeforeGroups mode.

**Comment by rutgerkok** [comment]
I should add a note that those settings don't work in the BeforeGroups mode.
