### ISSUE TITLE
Forge Build 164: getCalculatedBiome NullPointer

### ISSUE THREAD

**Issue by BakermanLP** [MCTCP/TerrainControl#473]
Crash report: http://pastebin.com/VL684vAs

I started a new world with absolutly no config under config/TerrainControl/worlds/...

The version 163 in jenkins doesn't have that problem.

**Comment by rutgerkok** [comment]
The Forge version has basically been rewritten by now by various other people (Zidane, Dockter, bloodmc), so I'm closing this issue.
