### ISSUE TITLE
Multiple surface blocks

### ISSUE THREAD

**Issue by MegaNarwhal** [MCTCP/TerrainControl#474]
It would be very useful to be able to specify multiple block types to be used for the surface in a biome. For example, I'm trying to make a biome where the ground is a mix of coarse dirt and grass and it seems the only way to do so is to use ores. Fine-grained control over the composition of the surface would be a much better solution.

**Comment by rutgerkok** [comment]
See the SurfaceAndGroundControl setting, it should be able to do this.

**Comment by MegaNarwhal** [comment]
I've tried configuring SurfaceAndGroundControl and the only result I've been able to get is smooth paths of material, not a random noise pattern. Am I missing something?
