### ISSUE TITLE
FORGE TC 164 with latest Forge (18.2139) - results in crash

### ISSUE THREAD

**Issue by melekaiah** [MCTCP/TerrainControl#475]
the following errors happened. 

running latest 1.10.2 forge 
with build 164 of terrain control. 

It starts fine, created a vanilla world with the standard biome files generated. 
stopped singleplayer. 
deleted region files. 
added new biomes and objects from the bukkit build, thinking the biomes and objects should still work(am i wrong). then set it up and checked every line of the ini file. and restarted. 

Boom following error!

[http://pastebin.com/nFFcBzyH]

we would love to get this running under 1.10.2 and under 1.11 are there any packs or has forge just relied totally on bop?

**Comment by MCPitman** [comment]
The 1.10 forge build does not work properly (I also get crashes when loading custom biomes).

As far as I know this is a known issue but it has taken months to get close to fixing it. Development seems to have stagnated lately so I wouldn't expect a fix any time soon :(

**Comment by melekaiah** [comment]
Well. I hope it does get fixed. I have a few talanted modders who would have loved to use this tool on our server. We loved it in bukkit and have missed it since moving over. 

Im gonna keep the hope up and m willing to help test. Dont know enough myself to fix it.

**Comment by melekaiah** [comment]
is this fix gonna work for 1.10.2 or do we have to move on to 1.11? got a whole mod pack based around 10.2 atm. and not ready to update.

**Comment by rutgerkok** [comment]
I'm afraid you'll need to move to 1.11.

**Comment by melekaiah** [comment]
ok thankyou for the info and for the update, we will revisit this plugin in 6 months or so when we can update all our other mods.

**Comment by bloodmc** [comment]
@melekaiah You can build my 1.10.2 version here
https://github.com/bloodmc/TerrainControl/tree/1.10.2

I just pushed a major refactor that I am planning to PR for 1.11.
