### ISSUE TITLE
Biome Bundle not working

### ISSUE THREAD

**Issue by PiggyPiglet** [MCTCP/TerrainControl#476]
Hi, im trying to use biome bundle but its not working. I type /mv create WorldName normal -g TerrainControl but it justs makes a vanilla world.

**Comment by rutgerkok** [comment]
Make sure to check the server console for errors.

**Comment by MCPitman** [comment]
Try typing "/mv create world normal -g TerrainControl".

The default name for a Biome Bundle world is 'world', not 'WorldName'.

**Comment by Dummiesman** [comment]
If you're attempting to use BiomeBundle on 1.11, then the issue may be that BiomeBundle includes an outdated version of TerrainControl. Try using TerrainControl for 1.11: http://forum.mctcp.com/t/terraincontrol-for-spigot-1-11/1324/10

**Comment by bloodmc** [comment]
Biome Bundle works fine with latest builds.

**Comment by AndrewAubury** [comment]
Gotta love that support time
