### ISSUE TITLE
Some blocks being replaced

### ISSUE THREAD

**Issue by Deebz96** [MCTCP/TerrainControl#478]
TerrainControl seems to replace some blocks with others on world generation. So far, I've noticed that WATER, LAVA, and SNOW all get replaced with STATIONARY_WATER, STATIONARY_LAVA, and SNOW_BLOCK respectively. Moreover, if WriteAll is specified in the .ini files, any instances of these blocks in the biome configuration files will be overwritten with these as well. Using WriteDisable prevents the overwrite issue, but TerrainControl still replaces these blocks in runtime regardless.

The stationary liquid issue causes waterfalls to fail, only showing the source block unless updated. And the snow issue manifests itself in Biome Bundle, which utilizes snow layers as plants in some biomes. This issue causes snow blocks to be spammed around the landscape instead.

**Comment by Deebz96** [comment]
Still unresolved.

**Comment by Deebz96** [comment]
Turns out SNOW is no longer referencing to the layer like it did in 1.10. Now it looks for SNOW_LAYER. Made this change in all of the biome files that use snow like that, and it looks proper again.

Still have issues with flowing liquids though.

**Comment by rutgerkok** [comment]
This should be fixed by b86388e80ed39dccdf8e2c2a5f37a2a85f71a53b.
