### ISSUE TITLE
Chunk is already being populated

### ISSUE THREAD

**Issue by MegaNarwhal** [MCTCP/TerrainControl#480]
I'm running WorldBorder to pre-generate my world (partly to reduce load, partly because some structures don't spawn mobs when TC is enabled) and I'm getting this error: http://pastebin.com/9HRCsXGU This will also occasionally happen when WorldBorder isn't running/installed. Latest TC build and latest Spigot 1.11.

**Comment by MegaNarwhal** [comment]
It appears as though this issue is related to the frequency at which chunks are populated. It happened every couple of minutes at a frequency of 160 chunks/sec, but it has been running at 40 chunks/sec for around 15 minutes without issue.

**Comment by rutgerkok** [comment]
Looks like a jungle tree is extending into unloaded chunks - this results in two chunks getting generated at the same time, and therefore the error. I hope I can do something, but for now you can add `PopulationBoundsCheck: false` to the WorldConfig.

**Comment by iiegit** [comment]
in the config files I saw a warning that setting this to false causes the world to generate differently depending on which direction you explore in, would this affect the terrain heightmap generation or possibly cause visible seams in the world?

**Comment by MegaNarwhal** [comment]
@iiegit It doesn't seem to have much effect. First screenshot is with it set to true, second is with it set to false and the terrain explored from a different direction.
![2016-11-30_18 31 09](https://cloud.githubusercontent.com/assets/2307465/20776164/ec4210fe-b72c-11e6-94ec-eef5fe011ef1.png)
![2016-11-30_18 35 04](https://cloud.githubusercontent.com/assets/2307465/20776165/ede87588-b72c-11e6-926e-05a383b02cac.png)

**Comment by rutgerkok** [comment]
I think I fixed the issue, could anyone test this?

Download: http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/169/default/
