### ISSUE TITLE
Rain falls in custom cold biomes, despite the biome temperature (1.11)

### ISSUE THREAD

**Issue by iiegit** [MCTCP/TerrainControl#484]
I am working with a FromImage map, and not using ReplaceToBiomeName. Even with the biome temperature set at 0.1 or 0.0, rain falls in the biome instead of snow. 

Vanilla cold biomes nearby get normal snowfall in them, only the custom biomes experience this issue.

**Comment by rutgerkok** [comment]
Yeah, this is because the Minecraft client ignores custom biomes, and displays them as if they were "Plains". And it never snows in the Plains biome...

There's no way for me to fix this, unfortunately.

**Comment by iiegit** [comment]
ok, no problem, thank you guys so much for creating this plugin
