### ISSUE TITLE
Issues with MultiVerse + TerrainControl

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#487]
**I get this error in console:**
http://hastebin.com/akiyedujar.sql

**This happens when I enter this command:**
/mv create test2 normal -g TerrainControl

**Versions:**
This server is running Paper version git-Paper-910 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[TerrainControl] Loading TerrainControl v2.8.2-SNAPSHOT
[Multiverse-Core] Loading Multiverse-Core v2.5-b719

**Comment by rutgerkok** [comment]
That build doesn't work on Minecraft 1.10. Try this build:

http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/164/default/
