### ISSUE TITLE
Map items do not show terrain

### ISSUE THREAD

**Issue by MegaNarwhal** [MCTCP/TerrainControl#492]
No matter where they are in the world, when players create a map it shows up like this:
![2016-12-21_23 06 27](https://cloud.githubusercontent.com/assets/2307465/21414911/25d4fe52-c7d2-11e6-92fd-6ed9341660c5.png)
In the End (which is not a TC world) this is what it looks like:
![2016-12-21_23 08 13](https://cloud.githubusercontent.com/assets/2307465/21414937/5e23c1b2-c7d2-11e6-85ed-febc60342d2f.png)
Latest TC build. This doesn't happen on a server without TC installed.

**Comment by MegaNarwhal** [comment]
Any idea when this might get fixed?

**Comment by Pokechu22** [comment]
I'm going to take a look at this (never looked into biomebundle's source before, but this is the kind of issue I enjoy digging into).  I recognize that texture as the texture used for maps made in the nether, so that will help when debugging.

**Comment by Pokechu22** [comment]
OK, first update: this only happens with the bukkit version, not the forge version (or if it does happen with forge, it doesn't happen in single-player).  And confirmed for 2.8.2-SNAPSHOT.
