### ISSUE TITLE
Don't use world name to decide which preset to use on the Forge 1.10 version

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MCTCP/TerrainControl#498]
Currently in the 1.10 Forge version to use Biome Bundle you must name your world 'world,' This is because the mod uses the world name to decide which preset is used. Biome Bundle only kicks in if your world is named world.

While this worked fine on the Spigot version since servers only have one world, but in single player it causes some issues.

Instead of using world name, it would be better if each preset is given it's own world generator. Currently to enable Biome Bundle you must select the 'Terrain Control' world generator and name your world 'world.' I recommend that instead you choose the 'Biome Bundle' world generator and the world name is irrelevant. If you have multiple presets installed, each one would be given a different world generator.

**Comment by rutgerkok** [comment]
For a world, TerrainControl uses the settings found in `.minecraft/config/TerrainControl/<worldname>`. You can go to the directory `.minecraft/config/TerrainControl/` and rename the `world` folder there.

**Comment by TheDeviantCrafter** [comment]
Can I use a wildcard to make it work on any world name? If not it's impossible to have more than one customized world per instance.

**Comment by rutgerkok** [comment]
If you want to have two worlds with the same configuration, you can copy the configuration files.

I know it's not really intuitive (most of TerrainControl isn't). However, TerrainControl is not really maintained anymore, so I think this will not be fixed.

**Comment by TheDeviantCrafter** [comment]
Since development has apparently started again, I'd like to request that this issue be re-opened.
