### ISSUE TITLE
Villages causing crashes 1.10.2 forge

### ISSUE THREAD

**Issue by mindcloud69** [MCTCP/TerrainControl#499]
https://gist.github.com/mindcloud69/1dbce8f987da9aeddb7f73bee2db99dc

**Comment by CreeperBossVJ** [comment]
Yeah this is my problem too...

**Comment by Meronat** [comment]
Was this on a server or a client version of Forge?

**Comment by CreeperBossVJ** [comment]
server

**Comment by mindcloud69** [comment]
both

**Comment by mindcloud69** [comment]
forge 12.18.3.2185

**Comment by Guinaro** [comment]
Here is another Crash Report: 
I restarted my world and everything booted up just fine. Running around without issues so far.

[crash-2017-03-17_06.07.15-server.txt](https://github.com/MCTCP/TerrainControl/files/849710/crash-2017-03-17_06.07.15-server.txt)
