### ISSUE TITLE
No Forge Biome Dictionary support for custom biomes

### ISSUE THREAD

**Issue by MCPitman** [MCTCP/TerrainControl#500]
Mods that try to place flora/fauna according to biome or climate cannot do this without [forge biome dictionary support](http://www.minecraftforum.net/forums/mapping-and-modding/mapping-and-modding-tutorials/1571414-how-to-use-the-forge-biomedictionary) and cause crashes when trying to spawn their content in Terrain Control biomes which do not have replacetobiomename set to a vanilla ID.

This is technically a feature request but I have reported it here since it causes crashes. Some crash reports are below:

IC2 Rubber Tree Generation crash: http://pastebin.com/eXbtZkZL

Pam's Havestcraft Beehive Generation crash: http://pastebin.com/iVrWjE7R

Also confirmed to happen with Mo' Creatures, and probably any other mods that try to detect Biome Dict tags to place worldgen features.

**Comment by twoworlds** [comment]
I can confirm this problem, in my tests the following mods caused a crash with Terrain Control:

- MoCreatures
- IC2
- Pam's Harvestcraft

**Comment by codewarrior0** [comment]
> IC2 Rubber Tree Generation crash: http://pastebin.com/eXbtZkZL

Getting a nearly identical crash.

```
terraincontrol-forge-2.8.2-1.10.2-B1.jar
industrialcraft-2-2.6.142-ex110.jar

Forge 12.18.3.2215
```

**Comment by LiskoSlayer63** [comment]
I can confirm this problem too when using [Mo' Creatures](http://pastebin.com/eEbETp4H) and also with [Roguelike Dungeons](http://pastebin.com/UV3bdcb4). I hope that this will be fixed soon.

**Comment by bloodmc** [comment]
This is resolved in PR https://github.com/MCTCP/TerrainControl/pull/545

**Comment by bloodmc** [comment]
Fixed in latest snapshot.
