### ISSUE TITLE
Terrain Control Drawing Information From Multiple World Files?

### ISSUE THREAD

**Issue by Kamiama** [MCTCP/TerrainControl#501]
I am using:
terraincontrol-forge-2.7.2 for Forge 1.7.10 v4

I was going through my world in F3 and found this:
![2017-01-06_19 32 09](https://cloud.githubusercontent.com/assets/24968256/21737519/979cc5ca-d447-11e6-97b4-f7c348a55c54.png)

The biome Archipelago is not a file in the world I am using, but in BiomeBundle, another world I have on my computer. For my world config it says that Lodgepole Forest is ID 40, not Archipelago.

**Comment by MCPitman** [comment]
Did you load a BBundle world and then go to main menu and then into another world present without restarting the client?

I believe this is a known bug that has been fixed for the 1.10.2 forge version of TC where biomes would not correctly un-register themselves when you quit to the main menu and load another preset.

**Comment by Kamiama** [comment]
This might be the case, but I cannot remember. I will do some testing and figure out if this is the problem.

**Comment by rutgerkok** [comment]
This cannot be fixed unfortunately. As Minecraft uses only one biome registry, biomes "leak" to other worlds. (Back when TerrainControl was designedm before Minecraft 1.2, this was not the case.)
