### ISSUE TITLE
Multiverse Not Recognising TerrainControl Generator

### ISSUE THREAD

**Issue by RaffMC** [MCTCP/TerrainControl#502]
When I try to create a terrain control world with multiverse ( /mvcreate Factions normal -g TerrainControl_) , it comes back with an error saying Invalid Generator! 'TerrainControl'. Aborting world creation.

**Comment by RaffMC** [comment]
I downgraded my multiverse and now it just says an internal error occured

**Comment by AlrightGamer42** [comment]
what versions do you have?

**Comment by RaffMC** [comment]
I use a fluctis 1.10.2 server and I was using the latest dev release of both multiverse and terrain control, because there was no release buildfor both of the that supported 1.10.2. Then I downgraded my terrain control to a non dev version (1.8/1.9) and got the first error (generator not found) error, then I downgraded my multiverse to the latest awesome build. And I got the second error, an internal error occurred

**Comment by AlrightGamer42** [comment]
hmm i am not sure. i would try going to http://forum.mctcp.com/c/help-and-support it is terrain controls official help page, it is hard to find the page but then the creator of terrain control usually responds to all the questions within a day or two, it has been really helpful to me. sorry i could not help you solve your problem.

**Comment by rutgerkok** [comment]
Make sure you have the correct version of TerrainControl for your version of Spigot. See [this page](https://github.com/MCTCP/TerrainControl/wiki/Version-history#recommended-build-for-each-minecraft-version).
