### ISSUE TITLE
Are builds 170 and 171 safe to use?

### ISSUE THREAD

**Issue by AaronMcHale** [MCTCP/TerrainControl#505]
According to http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/ the last two builds failed, one of them shows 1.11 compatibility, but a dev doesn't seem to have addressed whatever has caused them to fail and that was last month so are they safe to use for world generation on Bukkit/Spigot?

Thanks

**Comment by LanToaster** [comment]
I Doubt it. Because the Succesfull builds are all 2MB in Size, while the two Failed builds are only a few Kb in size.

I assume a Failed build on the BuildServer means the Compilation somewhere crashed/failed and isn Completed.

**Comment by rutgerkok** [comment]
Build server is fixed by now. Take a look at [this wiki page](https://github.com/MCTCP/TerrainControl/wiki/Version-history#recommended-build-for-each-minecraft-version) to see which build is best for you.
