### ISSUE TITLE
Path Block Crashes Forge

### ISSUE THREAD

**Issue by Kamiama** [MCTCP/TerrainControl#511]
When trying to use Surface and Ground Control with the path block in Forge 1.10.2, a crash results. I have fixed this by doing Replace Blocks, but I assume this is a bug.

I tried to find the log but it seems to have disappeared.

**Comment by Kamiama** [comment]
I found one of the logs: 

http://pastebin.com/xL4qMfTj

**Comment by rutgerkok** [comment]
The Forge version is more or less taken over by @PG85 - see his fork called [OpenTerrainGen](https://www.openterraingenerator.com/). I don't think this will be fixed by me.
