### ISSUE TITLE
Could not set generator for default world

### ISSUE THREAD

**Issue by Culvanen** [MCTCP/TerrainControl#512]
**Hi, I use TC 2.8.2 and Spigot 1.11.2. I have this error when world try to loading with TC.**

> [17:50:11 ERROR]: [TerrainControl] Could not set generator for default world 'Arandor': Plugin 'TerrainControl v2.8.2-SNAPSHOT
> java.lang.StringIndexOutOfBoundsException: String index out of range: -2
>         at java.lang.AbstractStringBuilder.deleteCharAt(Unknown Source) ~[?:1.8.0_121]
>         at java.lang.StringBuilder.deleteCharAt(Unknown Source) ~[?:1.8.0_121]
>         at com.khorn.terraincontrol.generator.surface.MultipleLayersSurfaceGenerator.toString(MultipleLayersSurfaceGenerator.java:97) ~[?:?]
>         at java.lang.String.valueOf(Unknown Source) ~[?:1.8.0_121]
>         at com.khorn.terraincontrol.configuration.settingType.Setting.write(Setting.java:64) ~[?:?]
>         at com.khorn.terraincontrol.configuration.io.RawSettingValue.ofPlainSetting(RawSettingValue.java:39) ~[?:?]
>         at com.khorn.terraincontrol.configuration.io.SimpleSettingsMap.putSetting(SimpleSettingsMap.java:183) ~[?:?]
>         at com.khorn.terraincontrol.configuration.BiomeConfig.writeConfigSettings(BiomeConfig.java:579) ~[?:?]
>         at com.khorn.terraincontrol.configuration.ConfigFile.getSettingsAsMap(ConfigFile.java:43) ~[?:?]
>         at com.khorn.terraincontrol.configuration.ServerConfigProvider.readAndWriteSettings(ServerConfigProvider.java:215) ~[?:?]
>         at com.khorn.terraincontrol.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:159) ~[?:?]
>         at com.khorn.terraincontrol.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:91) ~[?:?]
>         at com.khorn.terraincontrol.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:78) ~[?:?]
>         at com.khorn.terraincontrol.bukkit.TXPlugin.getDefaultWorldGenerator(TXPlugin.java:138) ~[?:?]
>         at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getGenerator(CraftServer.java:1236) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
>         at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:257) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
>         at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
>         at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Thanks for your work !

++Culvanen**

**Comment by rutgerkok** [comment]
Seems to be an error in your config files. One of your SurfaceAndGroundControl settings (I don't know in which biome, sorry!) is set to an invalid value.
