### ISSUE TITLE
WATER converts to STATIONARY_WATER

### ISSUE THREAD

**Issue by LanToaster** [MCTCP/TerrainControl#514]
At some Version Every Entry of: "WATER" defaults to "STATIONARY_WATER" in the Configs.

This is a Problem because "WATER" is Used to create WaterSource Blocks that start Flowing on Creation. While "STATIONARY_WATER" wont do that.

**Comment by MegaNarwhal** [comment]
Related to #479. I have created a temporary fix for this issue. https://www.dropbox.com/s/5340ty1ezhegj84/LiquidTick.jar?dl=0

**Comment by LanToaster** [comment]
Thanks alot. Even though in my Particular case it doesnt help. ^^

According to the MineCraft wiki, it seems like MineCraft changed the Material name for WATER and STATIONARY_WATER to FLOWING_WATER and WATER

I dunno if that helps if someone still wants to fix it.

**Comment by MegaNarwhal** [comment]
Minecraft's internal material names have no bearing on Bukkit's [Material](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) names. The Bukkit names are all that matters to Bukkit.

**Comment by LanToaster** [comment]
Still, I have tested it on my SpigotServer, where the Problem Occurs.

I used a Commandblock to set WATER, which doesnt start to flow without extra Blockupdate. And one with FLOWING_WATER, which starts to flow without Update.

**Comment by MegaNarwhal** [comment]
Command blocks don't use the Bukkit names. If generated water/lava (on cliff faces or in ravines) isn't flowing, try LiquidTick and make sure your TC world is specified in its config.yml.

**Comment by LanToaster** [comment]
As I said, in my Particular Problem, that doesnt help. Because I have WaterFlow Issuses not with single SourceBlocks, but with whole Rivers and Streams. :)

I´ll wait for a proper Fix for TC, or when I´m otherwise done with my World, I´ll change the Water Manually with MCEdit or something. :)

"Command blocks don't use the Bukkit names."
Everything must be so damn complicated. :/
Back in Beta everything was easier.

**Comment by rutgerkok** [comment]
Should be fixed in the [latest build](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/178/default/). (Note that that build requires Minecraft 1.12-pre5).
