### ISSUE TITLE
[Request] /tc map Biome Map Generation Tool for Forge Version

### ISSUE THREAD

**Issue by Guinaro** [MCTCP/TerrainControl#520]
Currently the bukkit version has a /tc map command, which is immensly useful in tweaking biome generation and seeing the effects easily of anything you tweak regarding biome size, rarity, borders, isles, ... .
For now I am using a bukkit version of Terraincontrol to tweak some settings, but since I am developing a modpack for Forge, it would ofcourse be much easier to do everything with the forge version.

Guinaro

**Comment by rutgerkok** [comment]
The Forge version is more or less taken over by @PG85 - see his fork called [OpenTerrainGen](https://www.openterraingenerator.com/). I don't think this will be fixed by me.
