### ISSUE TITLE
Server Crash / Freeze with latest Terrain Control

### ISSUE THREAD

**Issue by bloggy** [MCTCP/TerrainControl#522]
https://hastebin.com/putazomihi.md

Terrain Control Dev build from 12th April 2017

Server Crash with latest Terrain Control (it's the only plugin I have updated today, so assuming this must be terrain control). This crash never happened before.

**Comment by rutgerkok** [comment]
It's just that terrain generation is taking too long, and the server times out. You can increase the timeout time using the setting `timeout-time` in the spigot.yml file.
