### ISSUE TITLE
mctcp forums down

### ISSUE THREAD

**Issue by NLBlackEagle** [MCTCP/TerrainControl#526]
As the title says the forums for mctcp.com are down ( bad gateway ) 

Was this planned or?

**Comment by Culvanen** [comment]
Forum still down

**Comment by NLBlackEagle** [comment]
Indeed, The plan was that I took over, however I've set my eyes to a plan from online.net ( dedi server ) which is mostly out of stock. Once i can grab one for myself I will start by setting up an mailserver and discourse after this.

Once the above is done I can transfer over the forums.

@Timethor, think you could renew for another month? P.S. some help for the 15,99 dedi server at online.net would be great, if you are willing to I could give my phone number so you can whatsapp me once you see the package is in stock ( ill be asking the same from a couple of my most trustwhorty customers )

**Comment by MrSmity** [comment]
Sounds great cause it would be handy in the mean time I'll keep the plugin to the side and use my plan b

**Comment by NLBlackEagle** [comment]
The plugin still works and is maintained though :) If you would like support i have a discord channel for my TC package, feel free to use it while the forums are down, there are 30+- persons there which use terraincontrol. If people gather there you may be able to help each other and use the my github to ask questions if they can not figure it out. Here is the link https://discord.gg/8NBxYCD

**Comment by NLBlackEagle** [comment]
It's work-eat-dregora-sleep for me these past 2 weeks where dregora includes setting up the mailserver which I really need to host mctcp.com

Im on top of it guys!
