### ISSUE TITLE
Mineshafts above ground

### ISSUE THREAD

**Issue by DKrolls** [MCTCP/TerrainControl#533]
![2017-06-05_12 05 37](https://cloud.githubusercontent.com/assets/12780812/26794503/83c0e1ce-49e7-11e7-9013-a736235e30f5.png)
![2017-06-05_12 09 27](https://cloud.githubusercontent.com/assets/12780812/26794599/e841774e-49e7-11e7-9b99-a19947636548.png)

This happened with version v2.8.2-SNAPSHOT. All I did was generate a Mesa/Desert/Savanna-only world.

**Comment by agusztin** [comment]
Post your worldconfig.ini

**Comment by DKrolls** [comment]
https://pastebin.com/VjqFdXbL

**Comment by DKrolls** [comment]
But I do want mineshafts, just not on the surface.

**Comment by agusztin** [comment]
I don't know, sorry.

**Comment by MadCat64** [comment]
I've seen these before and just looked it up.  They are normal.  http://minecraft.gamepedia.com/Abandoned_mineshaft

**Comment by bloodmc** [comment]
This is normal as MadCat64 stated.
