### ISSUE TITLE
BiomeWetness 0.0 

### ISSUE THREAD

**Issue by Kirrasio** [MCTCP/TerrainControl#534]
Currently running 1.12 pre, and cleared my ReplaceToBiomeName to blank, set Biomewetness to 0.0 and it's still raining in the custom biome.  Current build 179 spigot 1.12 pre 5

 Biome wetness. Float value from 0.0 to 1.0.
 If this biome is a custom biome, and this value is set to 0, no rain will fall.
 On default biomes, this won't do anything except changing the grass and leaves colors slightly.
BiomeWetness: 0.0

**Comment by rutgerkok** [comment]
Unfortunately, the Minecraft client doesn't know that the wetness changed. The server doesn't (and cannot) tell the Minecraft client this. So this issue cannot be fixed without some client-side mod.
