### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [MCTCP/TerrainControl#535]
logs
https://gist.github.com/mat41997/03632a07843b93dfc88728a64143d9e3

timings
https://timings.aikar.co/?id=7c0c636d3ab14fe6b0bfe7a839b254e5

build 
http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/176/

torch
https://github.com/TorchSpigot/Torch
https://yivesmirror.com/downloads/torch

**Comment by KermMartian** [comment]
In other words, it appears TerrainControl needs to be updated to 1.12.

**Comment by mcsnetworks** [comment]
Any word on a 1.12 update?

**Comment by Culvanen** [comment]
You can download 1.12 for tc on page build

**Comment by KermMartian** [comment]
Perfect, thanks! This appears to work from our testing. Let us know if you need any comments or feedback as you aim for a stable release.

**Comment by bloodmc** [comment]
Fixed with latest build.
