### ISSUE TITLE
Terrain Control on Spigot 1.12 not working

### ISSUE THREAD

**Issue by smmmadden** [MCTCP/TerrainControl#537]
Hi - I've had several reports that the current build here is not working as it was built on pre5 and not the final GA release of 1.12. Can you repackage it and the I can update Spigot's Compatible Plugins and my spreadsheet showing it is?  Thanks -Steve

**Comment by Jamdog** [comment]
I can also attest that TC does not work on Spigot 1.12, having updated a 1.11.2 server that had TC running to 1.12, newly generated terrain is purely vanilla.

**Comment by bloodmc** [comment]
@smmmadden @Jamdog Does build 182 work?

**Comment by smmmadden** [comment]
I see there were updates made to the resource here, but it doesn't appear it is ready yet for mainstream testing.

**Comment by bloodmc** [comment]
Fixed in PR https://github.com/MCTCP/TerrainControl/pull/542
