### ISSUE TITLE
SpawnHeightOffset not working

### ISSUE THREAD

**Issue by Culvanen** [MCTCP/TerrainControl#538]
Hi,

SpawnHeightOffset in .bo3 file not working.

I using 1.12 of TerrainControl.

![image](https://user-images.githubusercontent.com/12481447/28460664-427e256e-6e13-11e7-8036-4a8926e0d267.png)

Thanks for your working

**Comment by Culvanen** [comment]
nobody to response ? this plugin is abandoned or (...) ?

**Comment by bloodmc** [comment]
dupe #467
