### ISSUE TITLE
Server Crashes With Spigot 1.12.1

### ISSUE THREAD

**Issue by craftyjai** [MCTCP/TerrainControl#541]
**Server Version:** Paper Spigot 1.12.1 (latest)
**Terrain Control Version:** 2.8.2 Snapshot
Description of Problem:
The server randomly crashes with this error in console [https://hastebin.com/murejebaca.vbs]( https://hastebin.com/murejebaca.vbs) There is no order or specific time that it crashes.

**Comment by andris155** [comment]
Already reported. https://github.com/MCTCP/TerrainControl/issues/540

**Comment by bloodmc** [comment]
@craftyjai @andris155 Does the latest snapshot solve your issue? If so , please close this ticket.

**Comment by bloodmc** [comment]
dupe #540
