### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by Yuuki2012** [MCTCP/TerrainControl#546]
https://paste2.org/FA9O5VN8
Ask if you need more information.

**Comment by bloodmc** [comment]
You need to paste the ENTIRE log.

**Comment by Yuuki2012** [comment]
https://paste2.org/sJy14kLw

**Comment by bloodmc** [comment]
https://gist.github.com/bloodmc/2e5117ea4199ffcff54f264126744044

No idea what you are doing with all those mod folders in your mods directory. Do NOT place forge in the mods folder, you need to run the installer and make sure you only have TerrainControl in it to test. Remove EVERYTHING else.

**Comment by bloodmc** [comment]
Unable to reproduce. Install Forge properly and you wont have an issue.
