### ISSUE TITLE
VirtualBiome names don't appear at Client

### ISSUE THREAD

**Issue by Dockter-Almura** [MCTCP/TerrainControl#547]
Using Version 2.8.3 and Sponge with both on server AND client. 

It doesn't appear that the virtual biome names are arriving at the client.  The biome I am in it appears that its getting the "replaceBiomeName" fields' value.

**Comment by rutgerkok** [comment]
This is intended (or at least, it was intended when the virtual biomes were added). Virtual biomes are only used during terrain generation. After that, they are "replaced" with their real counterpart. The client never sees the original biome, as it is already gone.
