### ISSUE TITLE
## INVALID CUSTOMSTRUCTURE - The object <name> isn't a structure: it has no branches ##

### ISSUE THREAD

**Issue by Arckdash115** [MCTCP/TerrainControl#548]
Hello,
I´m writting to get some help about an error that its making me mad, its about a custom structure i follow the tutorial and info about the BO3 objects and using WorldEdit create a schematic that i want to generate naturaly in a custom biome using BO3Tools  i convert the .schematic into a .bo3 but the file dont have any data about a structure just a lot of comments and when i run my test-server this error show up below the CustomStructure()
 **## INVALID CUSTOMSTRUCTURE - The object <name> isn't a structure: it has no branches ##** 
 even using BO3_BuildEdit2 another tool to convert schematics into bo3 that gives me a bo3 file with new info like coordinates xyz and the names of the blocks that make my structure the same error appear.

Here are my schematic, BO3 and BO2 files if you needed:
Schematic:
http://www.mediafire.com/file/lk390tat0zjcfuj/Nievoso.schematic
BO3 file:
http://www.mediafire.com/file/z3vfjyrn7i78uvw/Nievoso.bo3
BO2 file:
http://www.mediafire.com/file/poibu996r2ld4c7/Nievoso.bo2

Can i get some help i really want to generate custom structures in my biomes
Thanks and sorry if my english its bad :/

**Comment by bloodmc** [comment]
You are missing branches configuration in your config. Here is an example of a working BO3 custom structure
https://gist.github.com/bloodmc/b424dc109ac5ff95621f62732ce49bd0

Your BO3 is missing the following section

https://gist.github.com/bloodmc/b424dc109ac5ff95621f62732ce49bd0#file-beachbranching-bo3-L126-L135

Which is causing it to fail on line

https://github.com/MCTCP/TerrainControl/blob/master/common/src/main/java/com/khorn/terraincontrol/generator/resource/CustomStructureGen.java#L38

**Comment by Arckdash115** [comment]
Thank You so much, now i understand how the branches work and my structure finally generates in my biome. 

Thank You :D

**Comment by bloodmc** [comment]
No problem =).
