### ISSUE TITLE
Unable to load World [1.7.10]

### ISSUE THREAD

**Issue by Xaikii** [MCTCP/TerrainControl#550]
I was planning to use TerrainControl, followed the guide from the wiki. But there is an Issue I don't know why it's coming.

[https://pastebin.com/uwxDxNab](url)

It is an instant shutdown and I can't join the world.

I know I am using an old Minecraft Version but I'd ask for help/possible fix please.
Note: This is Forge Singleplayer.

**Comment by bloodmc** [comment]
1.7.10 is not supported.
