### ISSUE TITLE
Feature Request: Smart mineshafts

### ISSUE THREAD

**Issue by adamlaughlin** [MCTCP/TerrainControl#562]
I think it would be pretty immersive to see mineshaft spawns only originating from close to where villages were also placed.  I mean, who else is making those mines?

**Comment by rutgerkok** [comment]
It would certainly be nice, but this unfortunately is not how Minecraft's structure generator works. The village spawn code would need to be reworked to also spawn mineshafts.

TerrainControl generally only tweaks vanilla code, and does not rework it as that would be much more difficult. The plugin is already hard enough to maintain as is, and I don't think someone is going to take on the extra work required to support this.
