### ISSUE TITLE
Not getting rivers in FromImage

### ISSUE THREAD

**Issue by adamlaughlin** [MCTCP/TerrainControl#563]
Hey folks, love using TerrainControl.  Going to have months or years of fun with this.
I've been trying to fix something for a few days, and ultimately will resort to a fallback measure and a post because I'm starting to think this may be a bug.

When I am using the FromImage mode, my rivers are coming out as oceans.  I am using #0000FF in all rivers, all throughout my image file.  Everything else works perfectly.
For now, I have set the ImageFillBiome to River and hope to wait for a fix.

I did experiment with other river settings in other worlds before using the FromImage functionality, but in this world's WorldConfig.ini file I have since changed the river settings back to false (no longer improved or random) just in case the FromImage function was still reading those variables.  For now, the only fix I have is the ImageFillBiome.

Are you guys sure you set it to read River for #0000FF?  I discovered some out of date codes in the .bc files as well that I am going to post about when I wrap up deployment.

**Comment by rutgerkok** [comment]
TerrainControl is not hardcoded to interpret `#0000FF` as river. Instead, it uses whatever the `BiomeColor` or your river biome is. So make sure you have the `BiomeColor` of the River biome set to `#0000FF`.

**Comment by adamlaughlin** [comment]
Oh, good tip you added, glad I saw that.. maybe it's being used in my BiomeBundle world for another .bc file, yeah!  Rutger that possibly would not have occurred to me, thank you.  I was going to need the Ocean fill option very soon, glad you see your response.  That's definitely it.
