### ISSUE TITLE
terrain control how do i ReplacedBlocks:

### ISSUE THREAD

**Issue by SpeedRider** [MCTCP/TerrainControl#564]
i have trying so much to find out how to do it .
i have been trying to replace stone with Gray concrete but have not been able to.
ReplacedBlocks: (STONE,minecraft:concrete:8),(GRASS,minecraft:concrete_powder:13),(COBBLESTONE,minecraft:concrete:7),(SAND,minecraft:concrete_powder:4),(SAND,minecraft:concrete_powder:1),(GRAVEL,minecraft:concrete_powder:7),(STATIONARY_LAVA,STAINED_GLASS:1),(DIRT,minecraft:concrete_powder:12),(STATIONARY_WATER,STAINED_GLASS:3),(NETHERRACK,minecraft:concrete:15),(SOUL_SAND,minecraft:concrete_powder)
this is the thing i rote out but it not working i know i have done some thing rouge but i don't know what.

[OpenTerrainGenerator.zip](https://github.com/MCTCP/TerrainControl/files/1735576/OpenTerrainGenerator.zip)
i have upload the fill because i don't know if there some thing i have done rouge   

thank you for reading :)
have a good day please some if your able to help 
right it for a noob how has never done coding

**Comment by rutgerkok** [comment]
OpenTerrainGenerator? Please post it on their bug tracker. https://github.com/PG85/OpenTerrainGenerator/issues
