### ISSUE TITLE
MCTCP Forum down, don't know where else to post this

### ISSUE THREAD

**Issue by BleesTFE** [MCTCP/TerrainControl#566]
Also, a LOT of the wiki is out of date. Thank you for making this mod. And it is free too. I hope the forum get's up soon, please don't close this issue before telling me when forum will be up again.

**Comment by Timethor** [comment]
Hi @BleesTFE, check here: #569. TLDR: Forum is back up but in Read-Only mode until Apr. 1st when it will be taken down. No, it's not an april fool's joke ;)
