### ISSUE TITLE
WorldBiome loading.. Weird

### ISSUE THREAD

**Issue by YourCoal** [MCTCP/TerrainControl#568]
I have a custom biome that is alike the Extreme Hills, except that all stone and grass is replaced with Coal Blocks. When I load the world, the server reads the biome name correctly (Extreme Hills With Coal), but the foliage of trees appear brighter green than should, and in F3 says "Plains" in it. I tried ReplaceToBiomeName to see if that would fix it, however it then changed the entire biome generation, which is no good because a plugin I am developing needs to have the custom biome name. Is there some way to show the correct name in F3, and/or at least set the biome correctly to use the Extreme Hills colored foliage?

**Comment by rutgerkok** [comment]
The Minecraft client cannot display custom biomes, so it falls back to plains instead. Unfortunately, what you are asking is not possible without some client-side mod.
