### ISSUE TITLE
Forum and Build Server will be shut off on April 1st, 2018

### ISSUE THREAD

**Issue by Timethor** [MCTCP/TerrainControl#569]
I've loved contributing to this plugin over the years but I can no longer continue investing my time and money into it due to the other projects I'm involved in. I made a plea to the community for help hosting the forums about 6 months ago with no success. I've waited as long as I can for someone to come forward and help with either donations or hosting.

Current State of hosting:
- The forum software (Discourse) is currently online but in read-only mode.
- The build server is online, but the jobs to build on github push have been disabled for some time. Looks like another CI tool is being used these days.

Effective April 1st, 2018:
- The AWS server running forum.mctcp.com and build.mctcp.com will be shut down.
- The DNS entries for forum.mctcp.com and build.mctcp.com will be redirected to the main github repo page. If a different location is desired, I'm more than willing to update those accordingly
- All other DNS entries for the mctcp.com domain will remain unchanged unless otherwise noted as an update on this issue. 
- If someone maintaining this project wishes to own the mctcp.com domain, I can coordinate a transfer of ownership; otherwise I'll keep it for the foreseeable future.
- The forum data is available upon request to anyone willing to host a new discourse server; I will delete the data from my systems on October 1st, 2018.
- I doubt anyone wants the build server data, but that'll be available upon request to anyone looking for it; I will delete the data from my systems on October 1st, 2018.

It's been a pleasure,
Timethor

**Comment by rutgerkok** [comment]
I archived the BO3_Bulkedit and the Resources Index page on the wiki, so that at least those pages won't get lost. The other topics on the forums were all questions, discussions, etc, or have their information also posted elsewhere.

Thanks for hosting the forums for all these years, @Timethor!

**Comment by Dockter** [comment]
Hello,
AlmuraDev would be interested in taking this over if you would like.  We've made some massive improvements to TC over the past several months to make it more multi-world & client compatible.  I've personally been a user of TC for years and would be willing to give back to the community if we can.

**Comment by LanToaster** [comment]
As for BulkEdit what Rutger mentioned:
I moved BulkEdit to the OTG wiki:
http://openterraingen.wikia.com/wiki/Bo3_BulkEdit
Further Updates will be Posted there. 

Other than that. As I said before Timethor, I wish you best of Luck, and a Thanks for hosting the TC stuff for all this time. :)

**Comment by rutgerkok** [comment]
@LanToaster Great! I removed the page from the TerrainControl wiki, and added a link to the OTG wiki.

@Dockter That would be very nice, @Dockter! Did @Timethor already get in contact with you?

**Comment by Dockter** [comment]
I can be reach here:  https://discord.gg/uKeWpqh  or dockter@almuramc.com
