### ISSUE TITLE
Latest dev build: world entirely ocean in 1.12.2

### ISSUE THREAD

**Issue by 0ct0ber** [MCTCP/TerrainControl#570]
Using the latest development build, I've found that the world is almost entirely ocean, regardless of LandRarity settings. And a few mushroom island biomes...

This was tested on Bukkit and Spigot 1.12.2.

**Comment by rutgerkok** [comment]
Reproduced, a /tc map gives only oceans (with some islands) for the default settings.

**Comment by rutgerkok** [comment]
Fixed, download it here:

https://www.dropbox.com/s/38bo52vpdd3grsv/TerrainControl%20v.2.9.0dev.jar?dl=0

(The build server is going offline due to #569, so that's why I posted a link to my Dropbox.)
