### ISSUE TITLE
Where can I get version 2.8.2?

### ISSUE THREAD

**Issue by NorielSylvire** [MCTCP/TerrainControl#573]
I have a few plugins that require TerrainControl v2.8.2 to work. I searched in google for like and hour and could not find that exact version or higher at all. Does this make sense? Like, why would it require a version that does not exist yet?
Edit: Another hour later, yet havent found it. It either needs TC 2.8.2 for the version that you can get on Bukkit or needs TC 2.9.0 for the version that eccentric shared in the previous issue.
Edit2: Maybe I will use an older version of everything until version 2.8.2 is a bit easier to get.
Edit3: There is literally no way, because all the versions that work on minecraft 1.12 and bukkit 1.12 need at least TerrainControl 2.8.2, a version that either doesnt exist or is waaaaay harder to get than it should be so I guess I need to re build my server froms scrath to make it work in minecraft 1.11 to then make everything work. Yup
Edit4: This is incredible. I am using a 1.12 server, and I had to try every version of that plugin up to 1.9 compatible server to make it not need version 2.8.2
It seems to work, I'm using the said plugin, if the most basic features are available, I will declare myself satisfied....for now. You know, something is better than nothing.

**Comment by Craftaris** [comment]
I can send you the latest version for tests. Try adding me on discord - LTE#5165

**Comment by euanPC** [comment]
I also don't know where to get this but I have seen other people with the plugin commenting problems about it so is there any place where I can get it?
also on one of the plugins gave me a link to the update here it is http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/
